export type AppLanguage = 'pt' | 'en'

export const APP_LANGUAGES: Array<{ code: AppLanguage; name: string }> = [
  { code: 'pt', name: 'Português' },
  { code: 'en', name: 'English' },
]

/**
 * Idioma do app. Se o usuário JÁ escolheu (raw preenchido), respeita. Senão (1º uso), segue o
 * LOCALE do PC: português → 'pt', qualquer outro → 'en' (inglês é o padrão internacional, já que
 * a UI só tem pt/en). Ex.: PC em inglês/coreano abre em inglês, não em pt.
 */
export function appLanguage(raw?: string | null, locale?: string): AppLanguage {
  const sysLocale = locale ?? (typeof navigator !== 'undefined' ? navigator.language : '')
  const code = (raw && raw.trim()) ? raw : sysLocale
  return code?.split('-')[0]?.toLowerCase() === 'pt' ? 'pt' : 'en'
}

const UI = {
  pt: {
    appLanguage: 'Idioma do app',
    appLanguageNote: 'textos, menus e telas do software',
    explanationsLanguage: 'Explicações e traduções',
    explanationsNote: 'o tutor responde neste idioma',
    yourLanguage: 'Seu idioma',
    contentLanguage: 'Idioma do conteúdo',
    contentLanguageLabel: 'Idioma do áudio que você assiste',
    contentLanguageNote: '“Auto” detecta por trecho; fixe um idioma se a detecção errar (ex.: inglês transcrito como chinês).',
    configured: 'configurado',
    settings: 'Configurações',
    activeProvider: 'Provider Ativo',
    aiProviders: 'Provedores de IA — Sua chave, seus tokens',
    tutorAi: 'Tutor AI',
    transcription: 'Transcrição',
    configureProvider: 'Configure ao menos um provider acima para habilitar as funções.',
    ttsVoice: 'Voz TTS',
    engine: 'Motor',
    kokoroVoice: 'Voz Kokoro',
    kokoroNote: 'usada quando o texto estiver em ingles',
    kokoroFirstUse: 'O primeiro uso do Kokoro baixa o modelo local; depois palavras e frases ficam em cache.',
    shortcuts: 'Atalhos globais',
    about: 'Sobre',
    saved: 'Salvo',
    test: 'Testar',
    testing: 'Testando...',
    keyValid: 'Chave válida ✓',
    keyTestFailed: 'Falha no teste',
    logout: 'Sair da conta',
    logoutConfirm: 'Você precisará entrar de novo para usar o app.',
    audioLangTitle: 'Idioma do áudio — clique p/ alternar. Travar no idioma certo deixa a transcrição bem mais precisa (Auto pode errar/embaralhar).',
    audioSection: 'Áudio',
    micYourVoice: 'Microfone (sua voz)',
    micYourVoiceNote: 'Usado na prática de pronúncia (quando você fala).',
    transcribeSource: 'O que transcrever',
    transcribeSourceNote: 'A fonte que o app escuta e transcreve.',
    systemAudioOption: '🔊 Som do PC (vídeos, calls)',
    defaultMic: 'Microfone padrão',
    removeKey: 'Remover chave',
    getKey: 'Obter chave',
    cancel: 'Cancelar',
    edit: 'Editar',
    add: '+ Adicionar',
    save: 'Salvar',
    noneConfigured: 'nenhum configurado',
    dashboardTitle: 'Início',
    review: 'Revisão',
    tutorBoard: 'Tutor Board',
    floatingBar: 'Barra flutuante',
    welcome: 'Bem-vindo de volta',
    ready: 'Pronto para praticar hoje? Você tem',
    phrase: 'frase',
    phrases: 'frases',
    toReview: 'para revisar.',
    sessions: 'Sessões',
    streak: 'Sequência',
    days: 'dias',
    todayGoal: 'Meta de hoje',
    goalHit: 'Meta batida!',
    remaining: 'Faltam',
    startListeningHint: 'ligue a escuta com',
    reviewByLanguage: 'Revisar por idioma',
    nothingDue: 'Nada a revisar agora',
    dueSuffix: 'a revisar',
    upToDate: 'em dia',
    reviewAll: 'Revisar tudo',
    pending: 'pendentes',
    topMistakes: 'Palavras que mais erro',
    topMistakesEmpty: 'As palavras recorrentes aparecem aqui depois das primeiras práticas.',
    recentSessions: 'Sessões recentes',
    capturedSession: 'sessão capturada',
    quickShortcuts: 'Atalhos rápidos',
    showHideBar: 'Mostrar/esconder barra',
    startPrompt: 'Use',
    toStart: 'para começar.',
    // — Pronúncia (card do perfil + card "testar" do Dashboard + diagnóstico) —
    pronTestTitle: 'Testar minha pronúncia',
    pronTestSub: 'Leia uma frase em voz alta e receba um score real de fala + entonação.',
    start: 'Começar',
    pronProfileTitle: 'Seu perfil de pronúncia',
    pronProfileEmpty: 'Pratique algumas frases (no Tutor Board) para descobrir seus pontos fracos de pronúncia.',
    pronSoundsYouMiss: 'Sons que você mais erra',
    pronWordsToTrain: 'Palavras a treinar',
    pronTrainButton: 'Treinar pronúncia',
    listen: 'Ouvir',
    pronDiagTitle: 'Diagnóstico de pronúncia',
    pronDrillTitle: 'Treinar suas palavras fracas',
    pronDiagSubAi: 'a IA ouve o seu som, não só o texto',
    pronDiagSubDrill: 'leia cada palavra que você mais erra e receba o score',
    pronUnavailable: 'Diagnóstico ainda não disponível para',
    close: 'Fechar',
    readAloudFocus: 'Leia em voz alta — foco:',
    listenModel: 'Ouvir o modelo',
    wordByWord: 'Palavra a palavra',
    tips: 'Dicas',
    words: 'Palavras',
    intonation: 'Entonação',
    transcribing: 'Transcrevendo…',
    analyzing: 'Analisando sua pronúncia…',
    speak: 'Falar',
    stop: 'Parar',
    tryAgain: 'Tentar de novo',
    redo: 'Refazer',
    next: 'Próxima',
    nextSentence: 'Próxima frase',
    // — Tutor Board —
    waitingAudio: 'Aguardando áudio...',
    waitingAudioSub: 'As análises aparecerão aqui automaticamente.',
    capturedThisSession: 'capturadas desta sessão',
    speedTitle: 'Velocidade do áudio (Original/TTS). 0.8× é ótimo para treinar escuta.',
    chatWithTeacher: 'Conversar com o professor',
    teacherIn: 'Professor em',
    teacherReadyTitle: 'Converse com o professor sobre o que você assistiu',
    captureMore: 'Capture mais',
    toUnlockTeacher: 'para liberar o professor',
    knownWordsSuffix: 'conhecidas',
    coverage: 'cobertura',
    naturalSpeech: 'Fala natural',
    spokenPinyin: 'Pinyin falado',
    realPronunciation: 'Pronúncia real',
    speaking: 'Ouvindo',
    practice: 'Praticar',
    accuracy: 'de precisão',
    vocabulary: 'Vocabulário',
    analysisFailed: 'Análise falhou:',
    listenOriginalScene: 'Ouvir o áudio original da cena',
    loopTitle: 'Loop/Chorus: repete a frase 3× (lento→normal) com pausa para você repetir (shadowing)',
    listenTtsTitle: 'Ouvir voz sintetizada (TTS)',
    practicePronTitle: 'Praticar pronúncia',
    mark: 'Marcar',
    accents: 'Sotaques',
    nativeVoices: 'Nativos',
    nativeVoiceN: 'Voz',
    nativePronTitle: 'Pronúncia nativa (Forvo)',
    nativePronNote: 'Vozes de nativos reais. O Wikimedia/Lingua Libre já funciona grátis, sem chave. Adicione uma chave Forvo (tem plano grátis) para cobertura melhor.',
    iKnow: 'Conheço',
    learningWord: 'Aprendendo',
    ignoreWord: 'Ignorar',
    markAs: 'Marcar como',
    clickToUnmark: 'Clique para desmarcar',
    goodPronunciation: 'Boa pronúncia!',
    heard: 'Ouvi:',
    searchingMeaning: 'Buscando significado...',
    noMeaning: 'Sem significado disponível.',
    trainThisWord: 'Treinar esta palavra',
    listenOriginalWord: 'Ouvir a pronúncia original desta palavra',
    listenApproxWord: 'Ouvir um recorte aproximado desta palavra',
    listenWord: 'Ouvir palavra',
    listenSee: 'Ouvir/ver',
    knownWordTitle: 'Você marcou como conhecida',
    learningWordTitle: 'Você está aprendendo esta palavra',
    ignoreWordTitle: 'Ignorada (nome próprio etc.)',
    clickToHear: 'Clique para ouvir e ver o significado',
    badgeAllKnown: 'Você conhece todas as palavras desta frase',
    badgePlusOne: 'Ponto ideal "+1": só 1 palavra nova nesta frase',
    badgeNewWords: 'palavras novas nesta frase',
    milestoneRemaining: 'Faltam',
    milestoneForMark: 'para o marco de',
    milestoneWords: 'palavras',
    milestoneAllDone: 'Você passou de todos os marcos! 🎉',
    romanization: 'Romanização',
    transliteration: 'Transliteração',
    // — Floating Bar —
    tabTranscription: 'Transcrição',
    tabSession: 'Sessão',
    sessionTimeTitle: 'Tempo da sessão atual',
    live: 'AO VIVO',
    hide: 'Esconder',
    processing: 'Processando',
    listenStart: 'Escutar',
    autoPracticeTitle: 'Pausa o vídeo a cada frase para você treinar',
    autoPractice: 'Auto-treino',
    analyze: 'Analisar',
    level: 'Nível',
    speechThreshold: 'Limiar de fala',
    repeatSentence: 'Repita a frase',
    listenTtsClear: 'Ouvir voz sintetizada (clara/lenta)',
    listenMyRecording: 'Ouvir minha gravação',
    myVoice: 'Minha voz',
    recordingIn: 'Gravando em',
    recordingNow: 'Gravando - fale agora',
    evaluating: 'Avaliando...',
    clickRecordWhenReady: 'Clique em Gravar quando estiver pronto.',
    record: 'Gravar',
    repeatAgain: 'Repetir',
    continueWord: 'Continuar',
    skip: 'Pular',
    pressListenHint: 'Aperte Escutar e dê play no vídeo.',
    audioLabel: 'Áudio',
    capturing: 'Capturando...',
    downloadingVoice: 'Baixando voz local…',
    practiceSpeechHere: 'Suas falas de prática aparecem aqui.',
    practiceHint: 'Use "Praticar" no Tutor Board para gravar e comparar.',
    attempt: 'Tentativa',
    youSaid: 'Você falou',
    noSystemAudio: 'Sem áudio do sistema. Toque algo e tente de novo.',
    audioDisconnected: 'Áudio desconectado. Clique para reiniciar.',
    recorderError: 'Erro no gravador.',
    // — Professor Chat —
    voiceChatBasedOn: 'Conversa por voz — baseada em',
    fromThisSession: 'desta sessão',
    teacherThinking: 'Professor está pensando…',
    teacherUnavailable: 'Não consegui falar com o professor agora.',
    notEnoughOldContext: 'Ainda não há contexto antigo suficiente para compactar.',
    compacted: 'Compactado:',
    stopAndSend: 'Parar e enviar',
    timeLeftHint: 'restantes — toque em Parar e enviar quando terminar',
    getReady: 'Prepare-se…',
    sendingForTranscription: 'Enviando sua resposta para transcrição…',
    tapToAnswer: 'Toque e responda ao professor falando',
    whatToAdjust: 'O que ajustar',
    inSimilarSituations: 'Em situações parecidas',
    listenAgain: 'Ouvir de novo',
    betterWay: 'Forma melhor de responder',
    practiceAgain: 'Praticar de novo',
    contextUsed: 'Contexto usado',
    compact: 'Compactar',
    compactNowTitle: 'Compactar contexto agora',
    compactUnavailable: 'Compactação indisponível',
    messages: 'mensagens',
    tokensSpent: 'tokens gastos',
    today: 'hoje',
    calls: 'chamadas',
    // — Uso & Custo —
    usageCostTitle: 'Uso & Custo',
    estimatedSpend: 'Gasto estimado',
    thisMonth: 'este mês',
    usageTimeLabel: 'Tempo de uso',
    perSessionAvg: 'Custo médio/sessão',
    byProviderLabel: 'Por provedor',
    byFeatureLabel: 'Por recurso',
    audioMinutesLabel: 'min de áudio',
    sessionsLabel: 'sessões',
    usageCostNote: 'Estimativa BYOK (você usa sua própria chave) — valores aproximados conforme a tabela de preços.',
    usageCostEmpty: 'Ainda sem uso registrado. Capture algumas frases para ver o custo aqui.',
    // — Onboarding —
    onbSetupTitle: 'Configuração inicial',
    welcomeTo: 'Bem-vindo ao',
    whichLanguage: 'Qual idioma você quer aprender?',
    onbWelcomeDesc: 'Transforme qualquer áudio do PC em aulas — vídeos, dramas, podcasts. Pode escolher mais de um.',
    explanationsAppearIn: 'As explicações e traduções aparecem em:',
    yourLevelEach: 'Seu nível em cada idioma',
    levelEachDesc: 'Cada idioma tem o seu — ex.: Chinês iniciante e Inglês avançado.',
    levelIn: 'Nível em',
    pickAtLeastOne: 'Escolha ao menos um idioma',
    back: 'Voltar',
    onbStep2: 'Passo 2 — Conexão de IA (obrigatório)',
    connectApiKey: 'Conecte uma chave de API',
    onbApiKeyDesc: 'O Soaken é BYOK (você usa sua própria chave). Sem ela, transcrição e tutor não funcionam — por isso é necessária para continuar. Recomendado: Google Gemini ou Groq têm camada gratuita generosa.',
    checking: 'Verificando...',
    keyConfigured: 'Chave configurada ✓ Tudo pronto.',
    noKeyYet: 'Nenhuma chave ainda. Abra as Configurações para adicionar.',
    openSettings: 'Abrir Configurações',
    checkAgain: 'Verificar de novo',
    onbApiKeyHint: 'Configure uma chave nas Configurações e volte aqui — depois clique em “Verificar de novo”.',
    keyRequiredToContinue: 'É necessário configurar uma chave para continuar',
    allSet: 'Tudo pronto!',
    onbGoalPrefix: 'Sua meta de hoje:',
    onbCapture5: 'capturar 5 frases',
    onbOf: 'de',
    onbListenWatchHint: 'para ligar a escuta enquanto assiste algo.',
    onbMultiLangA: 'O app detecta o idioma do áudio automaticamente, então seus',
    onbMultiLangB: 'idiomas funcionam juntos.',
    startLearning: 'Começar a aprender',
    onbStep3: 'Passo 3 — Primeiros passos',
    startWithWriting: 'Comece pela escrita',
    focusOnSpeaking: 'Foco em conversação e produção',
    immersion: 'Imersão',
    ofYourLanguages: 'dos seus idiomas',
    startWithWritingSub: 'Aprender o sistema de escrita primeiro acelera tudo o que vem depois.',
    focusOnSpeakingSub: 'Você já entende — agora o salto é PRODUZIR: fala, pronúncia e conversa.',
    immersionSub: 'Conteúdo compreensível é o combustível — assista, capture, repita.',
    trainProduction: 'Treine a produção',
    onbBullet1: 'Capture diálogos reais e use o Loop/Chorus para repetir junto (shadowing).',
    onbBullet2: 'Grave sua fala e compare com o original — score de pronúncia e entonação.',
    onbBullet3: 'Marque palavras conhecidas e veja sua % de compreensão subir frase a frase.',
    onbBullet4: 'Ative o modo Auto para o vídeo pausar a cada frase e você responder.',
    channelsToStart: 'Canais para começar',
    levelBeginner: 'Começando do zero',
    levelKnowsScript: 'Já leio a escrita',
    levelIntermediate: 'Intermediário',
    levelAdvanced: 'Avançado / conversação',
    // — Review + componentes menores (Pass 6) —
    loadingWord: 'Carregando...',
    reviewDone: 'Revisão concluída!',
    youReviewed: 'Você revisou',
    captureAndComeBack: 'Capture frases no Tutor Board e volte mais tarde.',
    reviewedCount: 'revisadas',
    generatingVariations: 'Gerando variações...',
    seeVariations: 'Ver variações',
    otherWaysToSay: 'Outras formas de dizer',
    noVariations: 'Sem variações disponíveis.',
    showAnswer: 'Mostrar resposta',
    speakSentenceHint: 'Fale a frase em voz alta para treinar a pronúncia',
    gotWrong: 'Errei',
    hard: 'Difícil',
    easy: 'Fácil',
    pronToFix: 'Pronúncia a corrigir —',
    wordSingular: 'palavra',
    wordsPlural: 'palavras',
    listenOriginalSceneVoice: 'Ouvir a pronúncia original (voz da cena)',
    listenCorrectTts: 'Ouvir pronúncia correta (TTS)',
    drillHint: '🟢 voz original · 🔵 TTS. Repita cada palavra até acertar — o objetivo é zerar esta lista.',
    tones: 'Tons',
    toneFlat: 'alto plano',
    toneRise: 'sobe',
    toneFallRise: 'desce-sobe',
    toneFall: 'desce',
    toneNeutral: 'neutro',
    see: 'Ver',
    you: 'Você',
    hideComparison: 'Ocultar comparação',
    compareIntonation: 'Comparar entonação',
    analyzingRecording: 'Analisando sua gravação e o áudio original...',
    intonationLineHint: 'A linha mostra a entonação (subidas/descidas do tom). Azul = você, verde = original, amarelo = TTS.',
    generatingTtsBg: 'Gerando TTS em segundo plano...',
    ttsUnavailableNow: 'TTS indisponível agora; a comparação com o original continua válida.',
    noPitchDetected: 'Não detectamos entonação clara — fale um pouco mais alto e grave de novo.',
    cantReadAudio: 'Não foi possível ler este áudio para o gráfico — mas dá para comparar de ouvido:',
    chartUnavailable: 'Gráfico indisponível para este áudio — mas você pode comparar de ouvido:',
    decompose: 'Decompor',
    analyzingWord: 'Analisando',
    cantDecompose: 'Não foi possível decompor',
    strokes: 'traços',
    // — Auth (login/cadastro) —
    signIn: 'Entrar',
    createAccount: 'Criar conta',
    createYourAccount: 'Crie sua conta',
    continueWhereLeft: 'Continue de onde você parou.',
    startLearningSubtitles: 'Comece a aprender com legendas reais.',
    continueWithGoogle: 'Continuar com Google',
    orWithEmail: 'Ou com email',
    name: 'Nome',
    whatToCallYou: 'Como devemos te chamar?',
    password: 'Senha',
    yourPassword: 'Sua senha',
    createPassword: 'Crie uma senha (min. 6)',
    showPassword: 'Mostrar senha',
    minimize: 'Minimizar para a barra de tarefas',
    rememberMe: 'Lembrar de mim',
    forgotPassword: 'Esqueceu a senha?',
    iAcceptAria: 'Li e aceito os Termos de Uso e a Política de Privacidade',
    iAcceptThe: 'Li e aceito os',
    termsOfUse: 'Termos de Uso',
    andThe: 'e a',
    privacyPolicy: 'Política de Privacidade',
    pleaseWait: 'Aguarde...',
    newHere: 'Novo por aqui?',
    createOne: 'Criar uma conta',
    haveAccount: 'Já tem conta?',
    authFailed: 'Não foi possível autenticar.',
    confirmEmail: 'Confirme seu email para liberar o acesso.',
    accountCreated: 'Conta criada com sucesso. Entrando...',
    googleFailed: 'Não foi possível entrar com Google.',
    authFailedRetry: 'Não foi possível autenticar agora. Tente novamente.',
  },
  en: {
    appLanguage: 'App language',
    appLanguageNote: 'software text, menus and screens',
    explanationsLanguage: 'Explanations and translations',
    explanationsNote: 'the tutor answers in this language',
    yourLanguage: 'Your language',
    contentLanguage: 'Content language',
    contentLanguageLabel: 'Language of the audio you watch',
    contentLanguageNote: '“Auto” detects per segment; pin a language if detection is wrong (e.g., English transcribed as Chinese).',
    configured: 'configured',
    settings: 'Settings',
    activeProvider: 'Active Provider',
    aiProviders: 'AI Providers — Your key, your tokens',
    tutorAi: 'Tutor AI',
    transcription: 'Transcription',
    configureProvider: 'Configure at least one provider above to enable the features.',
    ttsVoice: 'TTS Voice',
    engine: 'Engine',
    kokoroVoice: 'Kokoro voice',
    kokoroNote: 'used when the text is in English',
    kokoroFirstUse: 'The first Kokoro use downloads the local model; after that, words and sentences are cached.',
    shortcuts: 'Global shortcuts',
    about: 'About',
    saved: 'Saved',
    test: 'Test',
    testing: 'Testing...',
    keyValid: 'Valid key ✓',
    keyTestFailed: 'Test failed',
    logout: 'Log out',
    logoutConfirm: 'You will need to sign in again to use the app.',
    audioLangTitle: 'Audio language — click to switch. Locking the right language makes transcription far more accurate (Auto can misdetect).',
    audioSection: 'Audio',
    micYourVoice: 'Microphone (your voice)',
    micYourVoiceNote: 'Used for pronunciation practice (when you speak).',
    transcribeSource: 'What to transcribe',
    transcribeSourceNote: 'The source the app listens to and transcribes.',
    systemAudioOption: '🔊 PC sound (videos, calls)',
    defaultMic: 'Default microphone',
    removeKey: 'Remove key',
    getKey: 'Get key',
    cancel: 'Cancel',
    edit: 'Edit',
    add: '+ Add',
    save: 'Save',
    noneConfigured: 'none configured',
    dashboardTitle: 'Home',
    review: 'Review',
    tutorBoard: 'Tutor Board',
    floatingBar: 'Floating bar',
    welcome: 'Welcome back',
    ready: 'Ready to practice today? You have',
    phrase: 'phrase',
    phrases: 'phrases',
    toReview: 'to review.',
    sessions: 'Sessions',
    streak: 'Streak',
    days: 'days',
    todayGoal: "Today's goal",
    goalHit: 'Goal complete!',
    remaining: 'Remaining',
    startListeningHint: 'start listening with',
    reviewByLanguage: 'Review by language',
    nothingDue: 'Nothing due right now',
    dueSuffix: 'to review',
    upToDate: 'up to date',
    reviewAll: 'Review all',
    pending: 'pending',
    topMistakes: 'Words I miss most',
    topMistakesEmpty: 'Recurring words will appear here after your first practice attempts.',
    recentSessions: 'Recent sessions',
    capturedSession: 'captured session',
    quickShortcuts: 'Quick shortcuts',
    showHideBar: 'Show/hide bar',
    startPrompt: 'Use',
    toStart: 'to start.',
    // — Pronunciation (profile card + Dashboard "test" card + diagnostic) —
    pronTestTitle: 'Test my pronunciation',
    pronTestSub: 'Read a sentence aloud and get a real speech + intonation score.',
    start: 'Start',
    pronProfileTitle: 'Your pronunciation profile',
    pronProfileEmpty: 'Practice a few sentences (in the Tutor Board) to discover your pronunciation weak spots.',
    pronSoundsYouMiss: 'Sounds you miss most',
    pronWordsToTrain: 'Words to train',
    pronTrainButton: 'Train pronunciation',
    listen: 'Listen',
    pronDiagTitle: 'Pronunciation diagnosis',
    pronDrillTitle: 'Train your weak words',
    pronDiagSubAi: 'the AI hears your sound, not just the text',
    pronDiagSubDrill: 'read each word you miss most and get the score',
    pronUnavailable: 'Diagnosis not available yet for',
    close: 'Close',
    readAloudFocus: 'Read aloud — focus:',
    listenModel: 'Listen to the model',
    wordByWord: 'Word by word',
    tips: 'Tips',
    words: 'Words',
    intonation: 'Intonation',
    transcribing: 'Transcribing…',
    analyzing: 'Analyzing your pronunciation…',
    speak: 'Speak',
    stop: 'Stop',
    tryAgain: 'Try again',
    redo: 'Redo',
    next: 'Next',
    nextSentence: 'Next sentence',
    // — Tutor Board —
    waitingAudio: 'Waiting for audio...',
    waitingAudioSub: 'Analyses will appear here automatically.',
    capturedThisSession: 'captured this session',
    speedTitle: 'Audio speed (Original/TTS). 0.8× is great for training listening.',
    chatWithTeacher: 'Chat with the teacher',
    teacherIn: 'Teacher in',
    teacherReadyTitle: 'Chat with the teacher about what you watched',
    captureMore: 'Capture',
    toUnlockTeacher: 'more to unlock the teacher',
    knownWordsSuffix: 'known',
    coverage: 'coverage',
    naturalSpeech: 'Natural speech',
    spokenPinyin: 'Spoken pinyin',
    realPronunciation: 'Real pronunciation',
    speaking: 'Playing',
    practice: 'Practice',
    accuracy: 'accuracy',
    vocabulary: 'Vocabulary',
    analysisFailed: 'Analysis failed:',
    listenOriginalScene: 'Listen to the original scene audio',
    loopTitle: 'Loop/Chorus: repeats the sentence 3× (slow→normal) with a pause for you to repeat (shadowing)',
    listenTtsTitle: 'Listen to synthesized voice (TTS)',
    practicePronTitle: 'Practice pronunciation',
    mark: 'Mark',
    accents: 'Accents',
    nativeVoices: 'Natives',
    nativeVoiceN: 'Voice',
    nativePronTitle: 'Native pronunciation (Forvo)',
    nativePronNote: 'Real native voices. Wikimedia/Lingua Libre already works for free, no key. Add a Forvo key (free tier available) for better coverage.',
    iKnow: 'I know',
    learningWord: 'Learning',
    ignoreWord: 'Ignore',
    markAs: 'Mark as',
    clickToUnmark: 'Click to unmark',
    goodPronunciation: 'Good pronunciation!',
    heard: 'Heard:',
    searchingMeaning: 'Looking up meaning...',
    noMeaning: 'No meaning available.',
    trainThisWord: 'Train this word',
    listenOriginalWord: 'Listen to the original pronunciation of this word',
    listenApproxWord: 'Listen to an approximate slice of this word',
    listenWord: 'Listen to word',
    listenSee: 'Listen/see',
    knownWordTitle: 'You marked this as known',
    learningWordTitle: 'You are learning this word',
    ignoreWordTitle: 'Ignored (proper noun, etc.)',
    clickToHear: 'Click to hear and see the meaning',
    badgeAllKnown: 'You know every word in this sentence',
    badgePlusOne: 'Sweet spot “+1”: only 1 new word in this sentence',
    badgeNewWords: 'new words in this sentence',
    milestoneRemaining: 'Missing',
    milestoneForMark: 'to reach the milestone of',
    milestoneWords: 'words',
    milestoneAllDone: 'You passed all milestones! 🎉',
    romanization: 'Romanization',
    transliteration: 'Transliteration',
    // — Floating Bar —
    tabTranscription: 'Transcript',
    tabSession: 'Session',
    sessionTimeTitle: 'Current session time',
    live: 'LIVE',
    hide: 'Hide',
    processing: 'Processing',
    listenStart: 'Listen',
    autoPracticeTitle: 'Pauses the video on each sentence so you can practice',
    autoPractice: 'Auto-practice',
    analyze: 'Analyze',
    level: 'Level',
    speechThreshold: 'Speech threshold',
    repeatSentence: 'Repeat the sentence',
    listenTtsClear: 'Listen to synthesized voice (clear/slow)',
    listenMyRecording: 'Listen to my recording',
    myVoice: 'My voice',
    recordingIn: 'Recording in',
    recordingNow: 'Recording - speak now',
    evaluating: 'Evaluating...',
    clickRecordWhenReady: 'Click Record when you’re ready.',
    record: 'Record',
    repeatAgain: 'Repeat',
    continueWord: 'Continue',
    skip: 'Skip',
    pressListenHint: 'Press Listen and play the video.',
    audioLabel: 'Audio',
    capturing: 'Capturing...',
    downloadingVoice: 'Downloading local voice…',
    practiceSpeechHere: 'Your practice attempts appear here.',
    practiceHint: 'Use "Practice" in the Tutor Board to record and compare.',
    attempt: 'Attempt',
    youSaid: 'You said',
    noSystemAudio: 'No system audio. Play something and try again.',
    audioDisconnected: 'Audio disconnected. Click to restart.',
    recorderError: 'Recorder error.',
    // — Professor Chat —
    voiceChatBasedOn: 'Voice chat — based on',
    fromThisSession: 'from this session',
    teacherThinking: 'Professor is thinking…',
    teacherUnavailable: 'I couldn’t reach the teacher right now.',
    notEnoughOldContext: 'Not enough old context to compact yet.',
    compacted: 'Compacted:',
    stopAndSend: 'Stop and send',
    timeLeftHint: 'left — tap Stop and send when done',
    getReady: 'Get ready…',
    sendingForTranscription: 'Sending your answer for transcription…',
    tapToAnswer: 'Tap and answer the teacher by speaking',
    whatToAdjust: 'What to adjust',
    inSimilarSituations: 'In similar situations',
    listenAgain: 'Listen again',
    betterWay: 'A better way to answer',
    practiceAgain: 'Practice again',
    contextUsed: 'Context used',
    compact: 'Compact',
    compactNowTitle: 'Compact context now',
    compactUnavailable: 'Compaction unavailable',
    messages: 'messages',
    tokensSpent: 'tokens spent',
    today: 'today',
    calls: 'calls',
    // — Usage & Cost —
    usageCostTitle: 'Usage & Cost',
    estimatedSpend: 'Estimated spend',
    thisMonth: 'this month',
    usageTimeLabel: 'Usage time',
    perSessionAvg: 'Avg cost/session',
    byProviderLabel: 'By provider',
    byFeatureLabel: 'By feature',
    audioMinutesLabel: 'min of audio',
    sessionsLabel: 'sessions',
    usageCostNote: 'BYOK estimate (you use your own key) — approximate values per the pricing table.',
    usageCostEmpty: 'No usage recorded yet. Capture a few sentences to see the cost here.',
    // — Onboarding —
    onbSetupTitle: 'Initial setup',
    welcomeTo: 'Welcome to',
    whichLanguage: 'Which language do you want to learn?',
    onbWelcomeDesc: 'Turn any PC audio into lessons — videos, dramas, podcasts. You can pick more than one.',
    explanationsAppearIn: 'Explanations and translations appear in:',
    yourLevelEach: 'Your level in each language',
    levelEachDesc: 'Each language has its own — e.g., Chinese beginner and English advanced.',
    levelIn: 'Level in',
    pickAtLeastOne: 'Pick at least one language',
    back: 'Back',
    onbStep2: 'Step 2 — AI connection (required)',
    connectApiKey: 'Connect an API key',
    onbApiKeyDesc: 'Soaken is BYOK (you use your own key). Without it, transcription and the tutor don’t work — so it’s required to continue. Recommended: Google Gemini or Groq have a generous free tier.',
    checking: 'Checking...',
    keyConfigured: 'Key configured ✓ All set.',
    noKeyYet: 'No key yet. Open Settings to add one.',
    openSettings: 'Open Settings',
    checkAgain: 'Check again',
    onbApiKeyHint: 'Set a key in Settings and come back here — then click “Check again”.',
    keyRequiredToContinue: 'A key is required to continue',
    allSet: 'All set!',
    onbGoalPrefix: 'Your goal today:',
    onbCapture5: 'capture 5 sentences',
    onbOf: 'of',
    onbListenWatchHint: 'to start listening while you watch something.',
    onbMultiLangA: 'The app detects the audio language automatically, so your',
    onbMultiLangB: 'languages work together.',
    startLearning: 'Start learning',
    onbStep3: 'Step 3 — First steps',
    startWithWriting: 'Start with writing',
    focusOnSpeaking: 'Focus on speaking and production',
    immersion: 'Immersion',
    ofYourLanguages: 'in your languages',
    startWithWritingSub: 'Learning the writing system first speeds up everything that comes after.',
    focusOnSpeakingSub: 'You already understand — now the leap is to PRODUCE: speech, pronunciation and conversation.',
    immersionSub: 'Comprehensible content is the fuel — watch, capture, repeat.',
    trainProduction: 'Train production',
    onbBullet1: 'Capture real dialogue and use Loop/Chorus to repeat along (shadowing).',
    onbBullet2: 'Record your speech and compare it to the original — pronunciation and intonation score.',
    onbBullet3: 'Mark known words and watch your comprehension % rise sentence by sentence.',
    onbBullet4: 'Turn on Auto mode so the video pauses on each sentence for you to answer.',
    channelsToStart: 'Channels to start with',
    levelBeginner: 'Starting from zero',
    levelKnowsScript: 'I can read the script',
    levelIntermediate: 'Intermediate',
    levelAdvanced: 'Advanced / conversation',
    // — Review + smaller components (Pass 6) —
    loadingWord: 'Loading...',
    reviewDone: 'Review complete!',
    youReviewed: 'You reviewed',
    captureAndComeBack: 'Capture sentences in the Tutor Board and come back later.',
    reviewedCount: 'reviewed',
    generatingVariations: 'Generating variations...',
    seeVariations: 'See variations',
    otherWaysToSay: 'Other ways to say it',
    noVariations: 'No variations available.',
    showAnswer: 'Show answer',
    speakSentenceHint: 'Say the sentence aloud to practice pronunciation',
    gotWrong: 'Got it wrong',
    hard: 'Hard',
    easy: 'Easy',
    pronToFix: 'Pronunciation to fix —',
    wordSingular: 'word',
    wordsPlural: 'words',
    listenOriginalSceneVoice: 'Listen to the original pronunciation (scene voice)',
    listenCorrectTts: 'Listen to the correct pronunciation (TTS)',
    drillHint: '🟢 original voice · 🔵 TTS. Repeat each word until you nail it — the goal is to clear this list.',
    tones: 'Tones',
    toneFlat: 'high flat',
    toneRise: 'rising',
    toneFallRise: 'fall-rise',
    toneFall: 'falling',
    toneNeutral: 'neutral',
    see: 'See',
    you: 'You',
    hideComparison: 'Hide comparison',
    compareIntonation: 'Compare intonation',
    analyzingRecording: 'Analyzing your recording and the original audio...',
    intonationLineHint: 'The line shows the intonation (pitch rises/falls). Blue = you, green = original, yellow = TTS.',
    generatingTtsBg: 'Generating TTS in the background...',
    ttsUnavailableNow: 'TTS unavailable now; the comparison with the original is still valid.',
    noPitchDetected: 'No clear intonation detected — speak a bit louder and record again.',
    cantReadAudio: 'Couldn’t read this audio for the chart — but you can compare by ear:',
    chartUnavailable: 'Chart unavailable for this audio — but you can compare by ear:',
    decompose: 'Break down',
    analyzingWord: 'Analyzing',
    cantDecompose: 'Couldn’t break down',
    strokes: 'strokes',
    // — Auth (login/signup) —
    signIn: 'Sign in',
    createAccount: 'Create account',
    createYourAccount: 'Create your account',
    continueWhereLeft: 'Continue where you left off.',
    startLearningSubtitles: 'Start learning with real subtitles.',
    continueWithGoogle: 'Continue with Google',
    orWithEmail: 'Or with email',
    name: 'Name',
    whatToCallYou: 'What should we call you?',
    password: 'Password',
    yourPassword: 'Your password',
    createPassword: 'Create a password (min. 6)',
    showPassword: 'Show password',
    minimize: 'Minimize to taskbar',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    iAcceptAria: 'I have read and accept the Terms of Use and the Privacy Policy',
    iAcceptThe: 'I have read and accept the',
    termsOfUse: 'Terms of Use',
    andThe: 'and the',
    privacyPolicy: 'Privacy Policy',
    pleaseWait: 'Please wait...',
    newHere: 'New here?',
    createOne: 'Create an account',
    haveAccount: 'Already have an account?',
    authFailed: 'Could not authenticate.',
    confirmEmail: 'Confirm your email to unlock access.',
    accountCreated: 'Account created successfully. Signing in...',
    googleFailed: 'Could not sign in with Google.',
    authFailedRetry: 'Could not authenticate right now. Please try again.',
  },
} as const

export type UiKey = keyof typeof UI.pt

export function uiText(lang: AppLanguage, key: UiKey): string {
  return UI[lang][key] ?? UI.pt[key]
}
