export type AppLanguage = 'pt' | 'en' | 'ko' | 'zh'

export const APP_LANGUAGES: Array<{ code: AppLanguage; name: string }> = [
  { code: 'en', name: 'English' },
  { code: 'pt', name: 'Português' },
  { code: 'ko', name: '한국어' },
  { code: 'zh', name: '中文' },
]

const APP_LANG_CODES: readonly string[] = ['pt', 'en', 'ko', 'zh']

/**
 * Idioma do app. Se o usuário JÁ escolheu (raw preenchido), respeita (pt/en/ko/zh). Senão (1º uso),
 * segue o LOCALE do PC mas só entre pt/en — ko/zh são OPT-IN (tradução parcial, resto cai no inglês),
 * então não auto-selecionamos pra não mostrar uma UI meio traduzida sem o usuário escolher.
 */
export function appLanguage(raw?: string | null, locale?: string): AppLanguage {
  if (raw && raw.trim()) {
    const c = raw.split(/[-_]/)[0].toLowerCase()
    if (APP_LANG_CODES.includes(c)) return c as AppLanguage
    return 'en'
  }
  const sysLocale = locale ?? (typeof navigator !== 'undefined' ? navigator.language : '')
  return sysLocale?.split(/[-_]/)[0]?.toLowerCase() === 'pt' ? 'pt' : 'en'
}

const UI = {
  pt: {
    appLanguage: 'Idioma do app',
    appLanguageNote: 'textos, menus e telas do software',
    explanationsLanguage: 'Explicações e traduções',
    explanationsNote: 'o tutor responde neste idioma',
    yourLanguage: 'Seu idioma',
    contentLanguage: 'Idioma do conteúdo',
    contentLanguageLabel: 'Idioma do áudio que você assiste',
    contentLanguageNote: '“Auto” detecta por trecho; fixe um idioma se a detecção errar (ex.: inglês transcrito como chinês).',
    configured: 'configurado',
    settings: 'Configurações',
    activeProvider: 'Provider Ativo',
    aiProviders: 'Provedores de IA — Sua chave, seus tokens',
    tutorAi: 'Tutor AI',
    transcription: 'Transcrição',
    configureProvider: 'Configure ao menos um provider acima para habilitar as funções.',
    ttsVoice: 'Voz TTS',
    engine: 'Motor',
    kokoroVoice: 'Voz Kokoro',
    kokoroNote: 'usada quando o texto estiver em ingles',
    kokoroFirstUse: 'O primeiro uso do Kokoro baixa o modelo local; depois palavras e frases ficam em cache.',
    shortcuts: 'Atalhos globais',
    about: 'Sobre',
    shortcutListen: 'Iniciar / parar escuta',
    shortcutDashboard: 'Abrir Início',
    shortcutSettings: 'Abrir Configurações',
    shortcutTutorBoard: 'Abrir Tutor Board',
    shortcutDock: 'Mostrar / esconder dock',
    shortcutPlayer: 'Pausar / retomar player',
    appTagline: 'Mergulhe no idioma',
    aboutDescription: 'Seu professor flutuante para qualquer idioma. O Soaken escuta qualquer áudio do PC — vídeos, calls, séries — e transforma em prática real de fala e pronúncia.',
    ttsLocalVoice: 'voz local em inglês',
    ttsMultiFallback: 'fallback multi-idioma',
    forvoKeyPlaceholder: 'Chave da API Forvo',
    saved: 'Salvo',
    test: 'Testar',
    testing: 'Testando...',
    keyValid: 'Chave válida ✓',
    keyTestFailed: 'Falha no teste',
    logout: 'Sair da conta',
    logoutConfirm: 'Você precisará entrar de novo para usar o app.',
    audioLangTitle: 'Idioma do áudio — clique p/ alternar. Travar no idioma certo deixa a transcrição bem mais precisa (Auto pode errar/embaralhar).',
    audioSection: 'Áudio',
    micYourVoice: 'Microfone (sua voz)',
    micYourVoiceNote: 'Usado na prática de pronúncia (quando você fala).',
    transcribeSource: 'O que transcrever',
    transcribeSourceNote: 'A fonte que o app escuta e transcreve.',
    systemAudioOption: '🔊 Som do PC (vídeos, calls)',
    defaultMic: 'Microfone padrão',
    removeKey: 'Remover chave',
    getKey: 'Obter chave',
    cancel: 'Cancelar',
    edit: 'Editar',
    add: '+ Adicionar',
    save: 'Salvar',
    noneConfigured: 'nenhum configurado',
    dashboardTitle: 'Início',
    review: 'Revisão',
    tutorBoard: 'Tutor Board',
    floatingBar: 'Barra flutuante',
    welcome: 'Bem-vindo de volta',
    ready: 'Pronto para praticar hoje? Você tem',
    phrase: 'frase',
    phrases: 'frases',
    toReview: 'para revisar.',
    sessions: 'Sessões',
    streak: 'Sequência',
    days: 'dias',
    todayGoal: 'Meta de hoje',
    goalHit: 'Meta batida!',
    remaining: 'Faltam',
    startListeningHint: 'ligue a escuta com',
    reviewByLanguage: 'Revisar por idioma',
    nothingDue: 'Nada a revisar agora',
    dueSuffix: 'a revisar',
    upToDate: 'em dia',
    reviewAll: 'Revisar tudo',
    pending: 'pendentes',
    topMistakes: 'Palavras que mais erro',
    topMistakesEmpty: 'As palavras recorrentes aparecem aqui depois das primeiras práticas.',
    recentSessions: 'Sessões recentes',
    capturedSession: 'sessão capturada',
    quickShortcuts: 'Atalhos rápidos',
    showHideBar: 'Mostrar/esconder barra',
    startPrompt: 'Use',
    toStart: 'para começar.',
    // — Pronúncia (card do perfil + card "testar" do Dashboard + diagnóstico) —
    pronTestTitle: 'Testar minha pronúncia',
    pronTestSub: 'Leia uma frase em voz alta e receba um score real de fala + entonação.',
    start: 'Começar',
    pronProfileTitle: 'Seu perfil de pronúncia',
    pronProfileEmpty: 'Pratique algumas frases (no Tutor Board) para descobrir seus pontos fracos de pronúncia.',
    pronSoundsYouMiss: 'Sons que você mais erra',
    pronWordsToTrain: 'Palavras a treinar',
    pronTrainButton: 'Treinar pronúncia',
    listen: 'Ouvir',
    pronDiagTitle: 'Diagnóstico de pronúncia',
    pronDrillTitle: 'Treinar suas palavras fracas',
    trainSessionMistakes: 'Treinar os erros desta sessão',
    pronDiagSubAi: 'a IA ouve o seu som, não só o texto',
    pronDiagSubDrill: 'leia cada palavra que você mais erra e receba o score',
    pronUnavailable: 'Diagnóstico ainda não disponível para',
    close: 'Fechar',
    readAloudFocus: 'Leia em voz alta — foco:',
    listenModel: 'Ouvir o modelo',
    wordByWord: 'Palavra a palavra',
    tips: 'Dicas',
    words: 'Palavras',
    intonation: 'Entonação',
    transcribing: 'Transcrevendo…',
    analyzing: 'Analisando sua pronúncia…',
    speak: 'Falar',
    stop: 'Parar',
    tryAgain: 'Tentar de novo',
    redo: 'Refazer',
    next: 'Próxima',
    nextSentence: 'Próxima frase',
    // — Tutor Board —
    waitingAudio: 'Aguardando áudio...',
    waitingAudioSub: 'As análises aparecerão aqui automaticamente.',
    capturedThisSession: 'capturadas desta sessão',
    speedTitle: 'Velocidade do áudio (Original/TTS). 0.8× é ótimo para treinar escuta.',
    chatWithTeacher: 'Conversar com o professor',
    teacherIn: 'Professor em',
    teacherReadyTitle: 'Converse com o professor sobre o que você assistiu',
    captureMore: 'Capture mais',
    toUnlockTeacher: 'para liberar o professor',
    knownWordsSuffix: 'conhecidas',
    coverage: 'cobertura',
    naturalSpeech: 'Fala natural',
    spokenPinyin: 'Pinyin falado',
    realPronunciation: 'Pronúncia real',
    speaking: 'Ouvindo',
    practice: 'Praticar',
    accuracy: 'de precisão',
    vocabulary: 'Vocabulário',
    analysisFailed: 'Análise falhou:',
    listenOriginalScene: 'Ouvir o áudio original da cena',
    loopTitle: 'Loop: repete a frase 3× na velocidade escolhida, com pausa para você repetir (shadowing)',
    listenTtsTitle: 'Ouvir voz sintetizada (TTS)',
    practicePronTitle: 'Praticar pronúncia',
    mark: 'Marcar',
    accents: 'Sotaques',
    nativeVoices: 'Nativos',
    nativeVoiceN: 'Voz',
    nativePronTitle: 'Pronúncia nativa (Forvo)',
    nativePronNote: 'Vozes de nativos reais. O Wikimedia/Lingua Libre já funciona grátis, sem chave. Adicione uma chave Forvo (tem plano grátis) para cobertura melhor.',
    iKnow: 'Conheço',
    learningWord: 'Aprendendo',
    ignoreWord: 'Ignorar',
    markAs: 'Marcar como',
    clickToUnmark: 'Clique para desmarcar',
    goodPronunciation: 'Boa pronúncia!',
    heard: 'Ouvi:',
    searchingMeaning: 'Buscando significado...',
    noMeaning: 'Sem significado disponível.',
    trainThisWord: 'Treinar esta palavra',
    listenOriginalWord: 'Ouvir a pronúncia original desta palavra',
    listenApproxWord: 'Ouvir um recorte aproximado desta palavra',
    listenWord: 'Ouvir palavra',
    listenSee: 'Ouvir/ver',
    knownWordTitle: 'Você marcou como conhecida',
    learningWordTitle: 'Você está aprendendo esta palavra',
    ignoreWordTitle: 'Ignorada (nome próprio etc.)',
    clickToHear: 'Clique para ouvir e ver o significado',
    badgeAllKnown: 'Você conhece todas as palavras desta frase',
    badgePlusOne: 'Ponto ideal "+1": só 1 palavra nova nesta frase',
    badgeNewWords: 'palavras novas nesta frase',
    milestoneRemaining: 'Faltam',
    milestoneForMark: 'para o marco de',
    milestoneWords: 'palavras',
    milestoneAllDone: 'Você passou de todos os marcos! 🎉',
    romanization: 'Romanização',
    transliteration: 'Transliteração',
    // — Floating Bar —
    tabTranscription: 'Transcrição',
    tabSession: 'Sessão',
    sessionTimeTitle: 'Tempo da sessão atual',
    live: 'AO VIVO',
    hide: 'Esconder',
    processing: 'Processando',
    listenStart: 'Escutar',
    autoPracticeTitle: 'Pausa o vídeo a cada frase para você treinar',
    autoPractice: 'Auto-treino',
    analyze: 'Analisar',
    level: 'Nível',
    speechThreshold: 'Limiar de fala',
    repeatSentence: 'Repita a frase',
    listenTtsClear: 'Ouvir voz sintetizada (clara/lenta)',
    listenMyRecording: 'Ouvir minha gravação',
    myVoice: 'Minha voz',
    recordingIn: 'Gravando em',
    recordingNow: 'Gravando - fale agora',
    evaluating: 'Avaliando...',
    clickRecordWhenReady: 'Clique em Gravar quando estiver pronto.',
    record: 'Gravar',
    repeatAgain: 'Repetir',
    continueWord: 'Continuar',
    skip: 'Pular',
    pressListenHint: 'Aperte Escutar e dê play no vídeo.',
    audioLabel: 'Áudio',
    capturing: 'Capturando...',
    downloadingVoice: 'Baixando voz local…',
    practiceSpeechHere: 'Suas falas de prática aparecem aqui.',
    practiceHint: 'Use "Praticar" no Tutor Board para gravar e comparar.',
    attempt: 'Tentativa',
    youSaid: 'Você falou',
    noSystemAudio: 'Sem áudio do sistema. Toque algo e tente de novo.',
    audioDisconnected: 'Áudio desconectado. Clique para reiniciar.',
    recorderError: 'Erro no gravador.',
    // — Professor Chat —
    voiceChatBasedOn: 'Conversa por voz — baseada em',
    fromThisSession: 'desta sessão',
    teacherThinking: 'Professor está pensando…',
    teacherUnavailable: 'Não consegui falar com o professor agora.',
    notEnoughOldContext: 'Ainda não há contexto antigo suficiente para compactar.',
    compacted: 'Compactado:',
    stopAndSend: 'Parar e enviar',
    timeLeftHint: 'restantes — toque em Parar e enviar quando terminar',
    getReady: 'Prepare-se…',
    sendingForTranscription: 'Enviando sua resposta para transcrição…',
    tapToAnswer: 'Toque e responda ao professor falando',
    whatToAdjust: 'O que ajustar',
    inSimilarSituations: 'Em situações parecidas',
    listenAgain: 'Ouvir de novo',
    betterWay: 'Forma melhor de responder',
    practiceAgain: 'Praticar de novo',
    contextUsed: 'Contexto usado',
    compact: 'Compactar',
    compactNowTitle: 'Compactar contexto agora',
    compactUnavailable: 'Compactação indisponível',
    messages: 'mensagens',
    tokensSpent: 'tokens gastos',
    today: 'hoje',
    calls: 'chamadas',
    // — Uso & Custo —
    usageCostTitle: 'Uso & Custo',
    estimatedSpend: 'Gasto estimado',
    thisMonth: 'este mês',
    usageTimeLabel: 'Tempo de uso',
    perSessionAvg: 'Custo médio/sessão',
    byProviderLabel: 'Por provedor',
    byFeatureLabel: 'Por recurso',
    audioMinutesLabel: 'min de áudio',
    sessionsLabel: 'sessões',
    usageCostNote: 'Estimativa BYOK (você usa sua própria chave) — valores aproximados conforme a tabela de preços.',
    usageCostEmpty: 'Ainda sem uso registrado. Capture algumas frases para ver o custo aqui.',
    // — Onboarding —
    onbSetupTitle: 'Configuração inicial',
    welcomeTo: 'Bem-vindo ao',
    whichLanguage: 'Qual idioma você quer aprender?',
    onbWelcomeDesc: 'Transforme qualquer áudio do PC em aulas — vídeos, dramas, podcasts. Pode escolher mais de um.',
    explanationsAppearIn: 'As explicações e traduções aparecem em:',
    yourLevelEach: 'Seu nível em cada idioma',
    levelEachDesc: 'Cada idioma tem o seu — ex.: Chinês iniciante e Inglês avançado.',
    levelIn: 'Nível em',
    pickAtLeastOne: 'Escolha ao menos um idioma',
    back: 'Voltar',
    onbStep2: 'Passo 2 — Conexão de IA (obrigatório)',
    connectApiKey: 'Conecte uma chave de API',
    onbApiKeyDesc: 'O Soaken é BYOK (você usa sua própria chave). Sem ela, transcrição e tutor não funcionam — por isso é necessária para continuar. Recomendado: Google Gemini ou Groq têm camada gratuita generosa.',
    checking: 'Verificando...',
    keyConfigured: 'Chave configurada ✓ Tudo pronto.',
    noKeyYet: 'Nenhuma chave ainda. Abra as Configurações para adicionar.',
    openSettings: 'Abrir Configurações',
    checkAgain: 'Verificar de novo',
    onbApiKeyHint: 'Configure uma chave nas Configurações e volte aqui — depois clique em “Verificar de novo”.',
    keyRequiredToContinue: 'É necessário configurar uma chave para continuar',
    allSet: 'Tudo pronto!',
    onbGoalPrefix: 'Sua meta de hoje:',
    onbCapture5: 'capturar 5 frases',
    onbOf: 'de',
    onbListenWatchHint: 'para ligar a escuta enquanto assiste algo.',
    onbMultiLangA: 'O app detecta o idioma do áudio automaticamente, então seus',
    onbMultiLangB: 'idiomas funcionam juntos.',
    startLearning: 'Começar a aprender',
    onbStep3: 'Passo 3 — Primeiros passos',
    startWithWriting: 'Comece pela escrita',
    focusOnSpeaking: 'Foco em conversação e produção',
    immersion: 'Imersão',
    ofYourLanguages: 'dos seus idiomas',
    startWithWritingSub: 'Aprender o sistema de escrita primeiro acelera tudo o que vem depois.',
    focusOnSpeakingSub: 'Você já entende — agora o salto é PRODUZIR: fala, pronúncia e conversa.',
    immersionSub: 'Conteúdo compreensível é o combustível — assista, capture, repita.',
    trainProduction: 'Treine a produção',
    onbBullet1: 'Capture diálogos reais e use o Loop/Chorus para repetir junto (shadowing).',
    onbBullet2: 'Grave sua fala e compare com o original — score de pronúncia e entonação.',
    onbBullet3: 'Marque palavras conhecidas e veja sua % de compreensão subir frase a frase.',
    onbBullet4: 'Ative o modo Auto para o vídeo pausar a cada frase e você responder.',
    channelsToStart: 'Canais para começar',
    levelBeginner: 'Começando do zero',
    levelKnowsScript: 'Já leio a escrita',
    levelIntermediate: 'Intermediário',
    levelAdvanced: 'Avançado / conversação',
    // — Review + componentes menores (Pass 6) —
    loadingWord: 'Carregando...',
    reviewDone: 'Revisão concluída!',
    youReviewed: 'Você revisou',
    captureAndComeBack: 'Capture frases no Tutor Board e volte mais tarde.',
    reviewedCount: 'revisadas',
    generatingVariations: 'Gerando variações...',
    seeVariations: 'Ver variações',
    otherWaysToSay: 'Outras formas de dizer',
    noVariations: 'Sem variações disponíveis.',
    showAnswer: 'Mostrar resposta',
    speakSentenceHint: 'Fale a frase em voz alta para treinar a pronúncia',
    gotWrong: 'Errei',
    hard: 'Difícil',
    easy: 'Fácil',
    pronToFix: 'Pronúncia a corrigir —',
    wordSingular: 'palavra',
    wordsPlural: 'palavras',
    listenOriginalSceneVoice: 'Ouvir a pronúncia original (voz da cena)',
    listenCorrectTts: 'Ouvir pronúncia correta (TTS)',
    drillHint: '🟢 voz original · 🔵 TTS. Repita cada palavra até acertar — o objetivo é zerar esta lista.',
    tones: 'Tons',
    toneFlat: 'alto plano',
    toneRise: 'sobe',
    toneFallRise: 'desce-sobe',
    toneFall: 'desce',
    toneNeutral: 'neutro',
    see: 'Ver',
    you: 'Você',
    hideComparison: 'Ocultar comparação',
    compareIntonation: 'Comparar entonação',
    analyzingRecording: 'Analisando sua gravação e o áudio original...',
    intonationLineHint: 'A linha mostra a entonação (subidas/descidas do tom). Azul = você, verde = original, amarelo = TTS.',
    generatingTtsBg: 'Gerando TTS em segundo plano...',
    ttsUnavailableNow: 'TTS indisponível agora; a comparação com o original continua válida.',
    noPitchDetected: 'Não detectamos entonação clara — fale um pouco mais alto e grave de novo.',
    cantReadAudio: 'Não foi possível ler este áudio para o gráfico — mas dá para comparar de ouvido:',
    chartUnavailable: 'Gráfico indisponível para este áudio — mas você pode comparar de ouvido:',
    decompose: 'Decompor',
    analyzingWord: 'Analisando',
    cantDecompose: 'Não foi possível decompor',
    strokes: 'traços',
    // — Auth (login/cadastro) —
    signIn: 'Entrar',
    createAccount: 'Criar conta',
    createYourAccount: 'Crie sua conta',
    continueWhereLeft: 'Continue de onde você parou.',
    startLearningSubtitles: 'Comece a aprender com legendas reais.',
    continueWithGoogle: 'Continuar com Google',
    orWithEmail: 'Ou com email',
    name: 'Nome',
    whatToCallYou: 'Como devemos te chamar?',
    password: 'Senha',
    yourPassword: 'Sua senha',
    createPassword: 'Crie uma senha (min. 6)',
    showPassword: 'Mostrar senha',
    minimize: 'Minimizar para a barra de tarefas',
    rememberMe: 'Lembrar de mim',
    forgotPassword: 'Esqueceu a senha?',
    iAcceptAria: 'Li e aceito os Termos de Uso e a Política de Privacidade',
    iAcceptThe: 'Li e aceito os',
    termsOfUse: 'Termos de Uso',
    andThe: 'e a',
    privacyPolicy: 'Política de Privacidade',
    pleaseWait: 'Aguarde...',
    newHere: 'Novo por aqui?',
    createOne: 'Criar uma conta',
    haveAccount: 'Já tem conta?',
    authFailed: 'Não foi possível autenticar.',
    confirmEmail: 'Confirme seu email para liberar o acesso.',
    accountCreated: 'Conta criada com sucesso. Entrando...',
    googleFailed: 'Não foi possível entrar com Google.',
    authFailedRetry: 'Não foi possível autenticar agora. Tente novamente.',
  },
  en: {
    appLanguage: 'App language',
    appLanguageNote: 'software text, menus and screens',
    explanationsLanguage: 'Explanations and translations',
    explanationsNote: 'the tutor answers in this language',
    yourLanguage: 'Your language',
    contentLanguage: 'Content language',
    contentLanguageLabel: 'Language of the audio you watch',
    contentLanguageNote: '“Auto” detects per segment; pin a language if detection is wrong (e.g., English transcribed as Chinese).',
    configured: 'configured',
    settings: 'Settings',
    activeProvider: 'Active Provider',
    aiProviders: 'AI Providers — Your key, your tokens',
    tutorAi: 'Tutor AI',
    transcription: 'Transcription',
    configureProvider: 'Configure at least one provider above to enable the features.',
    ttsVoice: 'TTS Voice',
    engine: 'Engine',
    kokoroVoice: 'Kokoro voice',
    kokoroNote: 'used when the text is in English',
    kokoroFirstUse: 'The first Kokoro use downloads the local model; after that, words and sentences are cached.',
    shortcuts: 'Global shortcuts',
    about: 'About',
    shortcutListen: 'Start / stop listening',
    shortcutDashboard: 'Open Home',
    shortcutSettings: 'Open Settings',
    shortcutTutorBoard: 'Open Tutor Board',
    shortcutDock: 'Show / hide dock',
    shortcutPlayer: 'Pause / resume player',
    appTagline: 'Dive into the language',
    aboutDescription: 'Your floating tutor for any language. Soaken listens to any audio on your PC — videos, calls, shows — and turns it into real speaking & pronunciation practice.',
    ttsLocalVoice: 'local English voice',
    ttsMultiFallback: 'multi-language fallback',
    forvoKeyPlaceholder: 'Forvo API key',
    saved: 'Saved',
    test: 'Test',
    testing: 'Testing...',
    keyValid: 'Valid key ✓',
    keyTestFailed: 'Test failed',
    logout: 'Log out',
    logoutConfirm: 'You will need to sign in again to use the app.',
    audioLangTitle: 'Audio language — click to switch. Locking the right language makes transcription far more accurate (Auto can misdetect).',
    audioSection: 'Audio',
    micYourVoice: 'Microphone (your voice)',
    micYourVoiceNote: 'Used for pronunciation practice (when you speak).',
    transcribeSource: 'What to transcribe',
    transcribeSourceNote: 'The source the app listens to and transcribes.',
    systemAudioOption: '🔊 PC sound (videos, calls)',
    defaultMic: 'Default microphone',
    removeKey: 'Remove key',
    getKey: 'Get key',
    cancel: 'Cancel',
    edit: 'Edit',
    add: '+ Add',
    save: 'Save',
    noneConfigured: 'none configured',
    dashboardTitle: 'Home',
    review: 'Review',
    tutorBoard: 'Tutor Board',
    floatingBar: 'Floating bar',
    welcome: 'Welcome back',
    ready: 'Ready to practice today? You have',
    phrase: 'phrase',
    phrases: 'phrases',
    toReview: 'to review.',
    sessions: 'Sessions',
    streak: 'Streak',
    days: 'days',
    todayGoal: "Today's goal",
    goalHit: 'Goal complete!',
    remaining: 'Remaining',
    startListeningHint: 'start listening with',
    reviewByLanguage: 'Review by language',
    nothingDue: 'Nothing due right now',
    dueSuffix: 'to review',
    upToDate: 'up to date',
    reviewAll: 'Review all',
    pending: 'pending',
    topMistakes: 'Words I miss most',
    topMistakesEmpty: 'Recurring words will appear here after your first practice attempts.',
    recentSessions: 'Recent sessions',
    capturedSession: 'captured session',
    quickShortcuts: 'Quick shortcuts',
    showHideBar: 'Show/hide bar',
    startPrompt: 'Use',
    toStart: 'to start.',
    // — Pronunciation (profile card + Dashboard "test" card + diagnostic) —
    pronTestTitle: 'Test my pronunciation',
    pronTestSub: 'Read a sentence aloud and get a real speech + intonation score.',
    start: 'Start',
    pronProfileTitle: 'Your pronunciation profile',
    pronProfileEmpty: 'Practice a few sentences (in the Tutor Board) to discover your pronunciation weak spots.',
    pronSoundsYouMiss: 'Sounds you miss most',
    pronWordsToTrain: 'Words to train',
    pronTrainButton: 'Train pronunciation',
    listen: 'Listen',
    pronDiagTitle: 'Pronunciation diagnosis',
    pronDrillTitle: 'Train your weak words',
    trainSessionMistakes: "Train this session's mistakes",
    pronDiagSubAi: 'the AI hears your sound, not just the text',
    pronDiagSubDrill: 'read each word you miss most and get the score',
    pronUnavailable: 'Diagnosis not available yet for',
    close: 'Close',
    readAloudFocus: 'Read aloud — focus:',
    listenModel: 'Listen to the model',
    wordByWord: 'Word by word',
    tips: 'Tips',
    words: 'Words',
    intonation: 'Intonation',
    transcribing: 'Transcribing…',
    analyzing: 'Analyzing your pronunciation…',
    speak: 'Speak',
    stop: 'Stop',
    tryAgain: 'Try again',
    redo: 'Redo',
    next: 'Next',
    nextSentence: 'Next sentence',
    // — Tutor Board —
    waitingAudio: 'Waiting for audio...',
    waitingAudioSub: 'Analyses will appear here automatically.',
    capturedThisSession: 'captured this session',
    speedTitle: 'Audio speed (Original/TTS). 0.8× is great for training listening.',
    chatWithTeacher: 'Chat with the teacher',
    teacherIn: 'Teacher in',
    teacherReadyTitle: 'Chat with the teacher about what you watched',
    captureMore: 'Capture',
    toUnlockTeacher: 'more to unlock the teacher',
    knownWordsSuffix: 'known',
    coverage: 'coverage',
    naturalSpeech: 'Natural speech',
    spokenPinyin: 'Spoken pinyin',
    realPronunciation: 'Real pronunciation',
    speaking: 'Playing',
    practice: 'Practice',
    accuracy: 'accuracy',
    vocabulary: 'Vocabulary',
    analysisFailed: 'Analysis failed:',
    listenOriginalScene: 'Listen to the original scene audio',
    loopTitle: 'Loop: repeats the sentence 3× at the chosen speed, with a pause for you to repeat (shadowing)',
    listenTtsTitle: 'Listen to synthesized voice (TTS)',
    practicePronTitle: 'Practice pronunciation',
    mark: 'Mark',
    accents: 'Accents',
    nativeVoices: 'Natives',
    nativeVoiceN: 'Voice',
    nativePronTitle: 'Native pronunciation (Forvo)',
    nativePronNote: 'Real native voices. Wikimedia/Lingua Libre already works for free, no key. Add a Forvo key (free tier available) for better coverage.',
    iKnow: 'I know',
    learningWord: 'Learning',
    ignoreWord: 'Ignore',
    markAs: 'Mark as',
    clickToUnmark: 'Click to unmark',
    goodPronunciation: 'Good pronunciation!',
    heard: 'Heard:',
    searchingMeaning: 'Looking up meaning...',
    noMeaning: 'No meaning available.',
    trainThisWord: 'Train this word',
    listenOriginalWord: 'Listen to the original pronunciation of this word',
    listenApproxWord: 'Listen to an approximate slice of this word',
    listenWord: 'Listen to word',
    listenSee: 'Listen/see',
    knownWordTitle: 'You marked this as known',
    learningWordTitle: 'You are learning this word',
    ignoreWordTitle: 'Ignored (proper noun, etc.)',
    clickToHear: 'Click to hear and see the meaning',
    badgeAllKnown: 'You know every word in this sentence',
    badgePlusOne: 'Sweet spot “+1”: only 1 new word in this sentence',
    badgeNewWords: 'new words in this sentence',
    milestoneRemaining: 'Missing',
    milestoneForMark: 'to reach the milestone of',
    milestoneWords: 'words',
    milestoneAllDone: 'You passed all milestones! 🎉',
    romanization: 'Romanization',
    transliteration: 'Transliteration',
    // — Floating Bar —
    tabTranscription: 'Transcript',
    tabSession: 'Session',
    sessionTimeTitle: 'Current session time',
    live: 'LIVE',
    hide: 'Hide',
    processing: 'Processing',
    listenStart: 'Listen',
    autoPracticeTitle: 'Pauses the video on each sentence so you can practice',
    autoPractice: 'Auto-practice',
    analyze: 'Analyze',
    level: 'Level',
    speechThreshold: 'Speech threshold',
    repeatSentence: 'Repeat the sentence',
    listenTtsClear: 'Listen to synthesized voice (clear/slow)',
    listenMyRecording: 'Listen to my recording',
    myVoice: 'My voice',
    recordingIn: 'Recording in',
    recordingNow: 'Recording - speak now',
    evaluating: 'Evaluating...',
    clickRecordWhenReady: 'Click Record when you’re ready.',
    record: 'Record',
    repeatAgain: 'Repeat',
    continueWord: 'Continue',
    skip: 'Skip',
    pressListenHint: 'Press Listen and play the video.',
    audioLabel: 'Audio',
    capturing: 'Capturing...',
    downloadingVoice: 'Downloading local voice…',
    practiceSpeechHere: 'Your practice attempts appear here.',
    practiceHint: 'Use "Practice" in the Tutor Board to record and compare.',
    attempt: 'Attempt',
    youSaid: 'You said',
    noSystemAudio: 'No system audio. Play something and try again.',
    audioDisconnected: 'Audio disconnected. Click to restart.',
    recorderError: 'Recorder error.',
    // — Professor Chat —
    voiceChatBasedOn: 'Voice chat — based on',
    fromThisSession: 'from this session',
    teacherThinking: 'Professor is thinking…',
    teacherUnavailable: 'I couldn’t reach the teacher right now.',
    notEnoughOldContext: 'Not enough old context to compact yet.',
    compacted: 'Compacted:',
    stopAndSend: 'Stop and send',
    timeLeftHint: 'left — tap Stop and send when done',
    getReady: 'Get ready…',
    sendingForTranscription: 'Sending your answer for transcription…',
    tapToAnswer: 'Tap and answer the teacher by speaking',
    whatToAdjust: 'What to adjust',
    inSimilarSituations: 'In similar situations',
    listenAgain: 'Listen again',
    betterWay: 'A better way to answer',
    practiceAgain: 'Practice again',
    contextUsed: 'Context used',
    compact: 'Compact',
    compactNowTitle: 'Compact context now',
    compactUnavailable: 'Compaction unavailable',
    messages: 'messages',
    tokensSpent: 'tokens spent',
    today: 'today',
    calls: 'calls',
    // — Usage & Cost —
    usageCostTitle: 'Usage & Cost',
    estimatedSpend: 'Estimated spend',
    thisMonth: 'this month',
    usageTimeLabel: 'Usage time',
    perSessionAvg: 'Avg cost/session',
    byProviderLabel: 'By provider',
    byFeatureLabel: 'By feature',
    audioMinutesLabel: 'min of audio',
    sessionsLabel: 'sessions',
    usageCostNote: 'BYOK estimate (you use your own key) — approximate values per the pricing table.',
    usageCostEmpty: 'No usage recorded yet. Capture a few sentences to see the cost here.',
    // — Onboarding —
    onbSetupTitle: 'Initial setup',
    welcomeTo: 'Welcome to',
    whichLanguage: 'Which language do you want to learn?',
    onbWelcomeDesc: 'Turn any PC audio into lessons — videos, dramas, podcasts. You can pick more than one.',
    explanationsAppearIn: 'Explanations and translations appear in:',
    yourLevelEach: 'Your level in each language',
    levelEachDesc: 'Each language has its own — e.g., Chinese beginner and English advanced.',
    levelIn: 'Level in',
    pickAtLeastOne: 'Pick at least one language',
    back: 'Back',
    onbStep2: 'Step 2 — AI connection (required)',
    connectApiKey: 'Connect an API key',
    onbApiKeyDesc: 'Soaken is BYOK (you use your own key). Without it, transcription and the tutor don’t work — so it’s required to continue. Recommended: Google Gemini or Groq have a generous free tier.',
    checking: 'Checking...',
    keyConfigured: 'Key configured ✓ All set.',
    noKeyYet: 'No key yet. Open Settings to add one.',
    openSettings: 'Open Settings',
    checkAgain: 'Check again',
    onbApiKeyHint: 'Set a key in Settings and come back here — then click “Check again”.',
    keyRequiredToContinue: 'A key is required to continue',
    allSet: 'All set!',
    onbGoalPrefix: 'Your goal today:',
    onbCapture5: 'capture 5 sentences',
    onbOf: 'of',
    onbListenWatchHint: 'to start listening while you watch something.',
    onbMultiLangA: 'The app detects the audio language automatically, so your',
    onbMultiLangB: 'languages work together.',
    startLearning: 'Start learning',
    onbStep3: 'Step 3 — First steps',
    startWithWriting: 'Start with writing',
    focusOnSpeaking: 'Focus on speaking and production',
    immersion: 'Immersion',
    ofYourLanguages: 'in your languages',
    startWithWritingSub: 'Learning the writing system first speeds up everything that comes after.',
    focusOnSpeakingSub: 'You already understand — now the leap is to PRODUCE: speech, pronunciation and conversation.',
    immersionSub: 'Comprehensible content is the fuel — watch, capture, repeat.',
    trainProduction: 'Train production',
    onbBullet1: 'Capture real dialogue and use Loop/Chorus to repeat along (shadowing).',
    onbBullet2: 'Record your speech and compare it to the original — pronunciation and intonation score.',
    onbBullet3: 'Mark known words and watch your comprehension % rise sentence by sentence.',
    onbBullet4: 'Turn on Auto mode so the video pauses on each sentence for you to answer.',
    channelsToStart: 'Channels to start with',
    levelBeginner: 'Starting from zero',
    levelKnowsScript: 'I can read the script',
    levelIntermediate: 'Intermediate',
    levelAdvanced: 'Advanced / conversation',
    // — Review + smaller components (Pass 6) —
    loadingWord: 'Loading...',
    reviewDone: 'Review complete!',
    youReviewed: 'You reviewed',
    captureAndComeBack: 'Capture sentences in the Tutor Board and come back later.',
    reviewedCount: 'reviewed',
    generatingVariations: 'Generating variations...',
    seeVariations: 'See variations',
    otherWaysToSay: 'Other ways to say it',
    noVariations: 'No variations available.',
    showAnswer: 'Show answer',
    speakSentenceHint: 'Say the sentence aloud to practice pronunciation',
    gotWrong: 'Got it wrong',
    hard: 'Hard',
    easy: 'Easy',
    pronToFix: 'Pronunciation to fix —',
    wordSingular: 'word',
    wordsPlural: 'words',
    listenOriginalSceneVoice: 'Listen to the original pronunciation (scene voice)',
    listenCorrectTts: 'Listen to the correct pronunciation (TTS)',
    drillHint: '🟢 original voice · 🔵 TTS. Repeat each word until you nail it — the goal is to clear this list.',
    tones: 'Tones',
    toneFlat: 'high flat',
    toneRise: 'rising',
    toneFallRise: 'fall-rise',
    toneFall: 'falling',
    toneNeutral: 'neutral',
    see: 'See',
    you: 'You',
    hideComparison: 'Hide comparison',
    compareIntonation: 'Compare intonation',
    analyzingRecording: 'Analyzing your recording and the original audio...',
    intonationLineHint: 'The line shows the intonation (pitch rises/falls). Blue = you, green = original, yellow = TTS.',
    generatingTtsBg: 'Generating TTS in the background...',
    ttsUnavailableNow: 'TTS unavailable now; the comparison with the original is still valid.',
    noPitchDetected: 'No clear intonation detected — speak a bit louder and record again.',
    cantReadAudio: 'Couldn’t read this audio for the chart — but you can compare by ear:',
    chartUnavailable: 'Chart unavailable for this audio — but you can compare by ear:',
    decompose: 'Break down',
    analyzingWord: 'Analyzing',
    cantDecompose: 'Couldn’t break down',
    strokes: 'strokes',
    // — Auth (login/signup) —
    signIn: 'Sign in',
    createAccount: 'Create account',
    createYourAccount: 'Create your account',
    continueWhereLeft: 'Continue where you left off.',
    startLearningSubtitles: 'Start learning with real subtitles.',
    continueWithGoogle: 'Continue with Google',
    orWithEmail: 'Or with email',
    name: 'Name',
    whatToCallYou: 'What should we call you?',
    password: 'Password',
    yourPassword: 'Your password',
    createPassword: 'Create a password (min. 6)',
    showPassword: 'Show password',
    minimize: 'Minimize to taskbar',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    iAcceptAria: 'I have read and accept the Terms of Use and the Privacy Policy',
    iAcceptThe: 'I have read and accept the',
    termsOfUse: 'Terms of Use',
    andThe: 'and the',
    privacyPolicy: 'Privacy Policy',
    pleaseWait: 'Please wait...',
    newHere: 'New here?',
    createOne: 'Create an account',
    haveAccount: 'Already have an account?',
    authFailed: 'Could not authenticate.',
    confirmEmail: 'Confirm your email to unlock access.',
    accountCreated: 'Account created successfully. Signing in...',
    googleFailed: 'Could not sign in with Google.',
    authFailedRetry: 'Could not authenticate right now. Please try again.',
  },
} as const

export type UiKey = keyof typeof UI.pt

// Korean/Chinese: traduções PARCIAIS (núcleo). O que faltar cai no inglês (fallback). Preencher
// incrementalmente — não precisa ter as 340 chaves pra a opção funcionar.
const UI_KO: Partial<Record<UiKey, string>> = {
  appLanguage: '앱 언어', appLanguageNote: '소프트웨어 텍스트, 메뉴, 화면',
  explanationsLanguage: '설명 및 번역', explanationsNote: '튜터가 이 언어로 답합니다',
  yourLanguage: '내 언어', contentLanguage: '콘텐츠 언어',
  contentLanguageLabel: '시청하는 오디오의 언어',
  contentLanguageNote: '"자동"은 구간별로 감지합니다. 감지가 틀리면(예: 영어를 중국어로 인식) 언어를 고정하세요.',
  configured: '설정됨', settings: '설정', activeProvider: '활성 제공자',
  aiProviders: 'AI 제공자 — 내 키, 내 토큰', tutorAi: '튜터 AI', transcription: '전사',
  configureProvider: '기능을 사용하려면 위에서 제공자를 최소 한 개 설정하세요.',
  ttsVoice: 'TTS 음성', engine: '엔진', kokoroVoice: 'Kokoro 음성',
  kokoroNote: '텍스트가 영어일 때 사용됩니다',
  kokoroFirstUse: 'Kokoro를 처음 쓰면 로컬 모델을 내려받습니다. 이후 단어·문장은 캐시됩니다.',
  shortcuts: '전역 단축키', about: '정보', saved: '저장됨', test: '테스트', testing: '테스트 중...',
  shortcutListen: '듣기 시작 / 정지', shortcutDashboard: '홈 열기', shortcutSettings: '설정 열기',
  shortcutTutorBoard: '튜터 보드 열기', shortcutDock: '독 표시 / 숨기기', shortcutPlayer: '플레이어 일시정지 / 재개',
  appTagline: '언어에 빠져드세요',
  aboutDescription: '어떤 언어든 위한 플로팅 튜터. Soaken은 PC의 모든 오디오(영상, 통화, 드라마)를 듣고 실제 말하기·발음 연습으로 바꿔줍니다.',
  ttsLocalVoice: '로컬 영어 음성', ttsMultiFallback: '다국어 폴백', forvoKeyPlaceholder: 'Forvo API 키',
  keyValid: '유효한 키 ✓', keyTestFailed: '테스트 실패', logout: '로그아웃',
  logoutConfirm: '앱을 사용하려면 다시 로그인해야 합니다.',
  audioLangTitle: '오디오 언어 — 클릭하여 전환. 올바른 언어로 고정하면 전사가 훨씬 정확해집니다(자동은 오인식 가능).',
  audioSection: '오디오', micYourVoice: '마이크 (내 목소리)',
  micYourVoiceNote: '발음 연습(말할 때)에 사용됩니다.', transcribeSource: '무엇을 전사할지',
  transcribeSourceNote: '앱이 듣고 전사하는 소스입니다.', systemAudioOption: '🔊 PC 소리 (영상, 통화)',
  defaultMic: '기본 마이크', removeKey: '키 제거', getKey: '키 받기', cancel: '취소', edit: '편집',
  add: '+ 추가', save: '저장', noneConfigured: '설정 안 됨', dashboardTitle: '홈', review: '복습',
  tutorBoard: '튜터 보드', floatingBar: '플로팅 바', welcome: '다시 오신 걸 환영합니다',
  ready: '오늘 연습할 준비됐나요? 복습할 문장이', phrase: '문장', phrases: '문장', toReview: '개 있습니다.',
  sessions: '세션', streak: '연속', days: '일', todayGoal: '오늘의 목표', goalHit: '목표 달성!',
  remaining: '남음', startListeningHint: '듣기 시작:', reviewByLanguage: '언어별 복습',
  nothingDue: '지금은 복습할 게 없습니다', dueSuffix: '복습', upToDate: '최신', reviewAll: '모두 복습',
  pending: '대기', topMistakes: '가장 자주 틀리는 단어', topMistakesEmpty: '첫 연습 후 자주 틀리는 단어가 여기 표시됩니다.',
  recentSessions: '최근 세션', capturedSession: '캡처한 세션', quickShortcuts: '빠른 단축키',
  showHideBar: '바 표시/숨기기', startPrompt: '사용:', toStart: '시작.',
  pronTestTitle: '내 발음 테스트', pronTestSub: '문장을 소리 내어 읽고 실제 발음 + 억양 점수를 받으세요.',
  start: '시작', pronProfileTitle: '내 발음 프로필',
  pronProfileEmpty: '튜터 보드에서 문장을 몇 개 연습하면 약한 발음 지점을 찾을 수 있습니다.',
  pronSoundsYouMiss: '가장 자주 놓치는 발음', pronWordsToTrain: '연습할 단어', pronTrainButton: '발음 연습',
  listen: '듣기', pronDiagTitle: '발음 진단', pronDrillTitle: '약한 단어 연습', trainSessionMistakes: '이 세션의 실수 연습',
  pronDiagSubAi: 'AI가 텍스트뿐 아니라 당신의 소리를 듣습니다', pronDiagSubDrill: '자주 틀리는 단어를 읽고 점수를 받으세요',
  pronUnavailable: '아직 진단을 사용할 수 없습니다:', close: '닫기', readAloudFocus: '소리 내어 읽기 — 집중:',
  listenModel: '모델 듣기', wordByWord: '단어별', tips: '팁', words: '단어', intonation: '억양',
  transcribing: '전사 중…', analyzing: '발음 분석 중…', speak: '말하기', stop: '정지', tryAgain: '다시 시도',
  redo: '다시', next: '다음', nextSentence: '다음 문장', waitingAudio: '오디오 대기 중...',
  waitingAudioSub: '분석이 여기에 자동으로 표시됩니다.', capturedThisSession: '이번 세션 캡처',
  speedTitle: '오디오 속도(원본/TTS). 듣기 연습에는 0.8×가 좋습니다.', chatWithTeacher: '선생님과 대화',
  teacherIn: '선생님 언어', teacherReadyTitle: '시청한 내용에 대해 선생님과 대화하세요',
  captureMore: '캡처', toUnlockTeacher: '개 더 하면 선생님이 열립니다', knownWordsSuffix: '아는 단어',
  coverage: '이해도', naturalSpeech: '자연스러운 말', spokenPinyin: '발화 병음', realPronunciation: '실제 발음',
  speaking: '재생 중', practice: '연습', accuracy: '정확도', vocabulary: '어휘', analysisFailed: '분석 실패:',
  listenOriginalScene: '원본 장면 오디오 듣기',
  loopTitle: '루프: 선택한 속도로 문장을 3회 반복하고, 따라 말할 수 있게 멈춥니다(섀도잉)',
  listenTtsTitle: '합성 음성(TTS) 듣기', practicePronTitle: '발음 연습', mark: '표시', accents: '악센트',
  nativeVoices: '원어민', nativeVoiceN: '음성', nativePronTitle: '원어민 발음 (Forvo)',
  nativePronNote: '실제 원어민 음성. Wikimedia/Lingua Libre는 키 없이 무료로 작동합니다. 더 나은 커버리지를 원하면 Forvo 키(무료 등급 있음)를 추가하세요.',
  iKnow: '알아요', learningWord: '학습 중', ignoreWord: '무시', markAs: '표시:', clickToUnmark: '클릭하여 해제',
  goodPronunciation: '좋은 발음이에요!', heard: '들린 내용:', searchingMeaning: '뜻 찾는 중...',
  noMeaning: '뜻을 찾을 수 없습니다.', trainThisWord: '이 단어 연습', listenOriginalWord: '이 단어의 원본 발음 듣기',
  listenApproxWord: '이 단어의 대략적인 구간 듣기', listenWord: '단어 듣기', listenSee: '듣기/보기',
  knownWordTitle: '아는 단어로 표시함', learningWordTitle: '이 단어를 학습 중', ignoreWordTitle: '무시됨(고유명사 등)',
  clickToHear: '클릭하여 듣고 뜻 보기', badgeAllKnown: '이 문장의 모든 단어를 압니다',
  badgePlusOne: '딱 좋은 "+1": 이 문장에 새 단어가 1개뿐', badgeNewWords: '개의 새 단어', milestoneRemaining: '남음',
  milestoneForMark: '도달까지', milestoneWords: '단어', milestoneAllDone: '모든 마일스톤을 통과했어요! 🎉',
  romanization: '로마자', transliteration: '음역', tabTranscription: '전사', tabSession: '세션',
  sessionTimeTitle: '현재 세션 시간', live: 'LIVE', hide: '숨기기', processing: '처리 중', listenStart: '듣기',
  autoPracticeTitle: '문장마다 영상을 멈춰 연습할 수 있게 합니다', autoPractice: '자동 연습', analyze: '분석',
  level: '레벨', speechThreshold: '음성 임계값', repeatSentence: '문장 반복',
  listenTtsClear: '합성 음성 듣기(또렷하게/천천히)', listenMyRecording: '내 녹음 듣기', myVoice: '내 목소리',
  recordingIn: '녹음 시작까지', recordingNow: '녹음 중 - 지금 말하세요', evaluating: '평가 중...',
  clickRecordWhenReady: '준비되면 녹음을 클릭하세요.', record: '녹음', repeatAgain: '반복', continueWord: '계속',
  skip: '건너뛰기', pressListenHint: '듣기를 누르고 영상을 재생하세요.', audioLabel: '오디오', capturing: '캡처 중...',
  downloadingVoice: '로컬 음성 내려받는 중…', practiceSpeechHere: '연습 기록이 여기에 표시됩니다.',
  practiceHint: '튜터 보드의 "연습"으로 녹음하고 비교하세요.', attempt: '시도', youSaid: '당신이 말한 것',
  noSystemAudio: '시스템 오디오가 없습니다. 무언가 재생하고 다시 시도하세요.',
  audioDisconnected: '오디오 연결 끊김. 클릭하여 다시 시작.', recorderError: '녹음 오류.',
  voiceChatBasedOn: '음성 대화 — 기반:', fromThisSession: '이번 세션에서', teacherThinking: '선생님이 생각 중…',
  teacherUnavailable: '지금 선생님에게 연결할 수 없습니다.', notEnoughOldContext: '아직 압축할 이전 맥락이 부족합니다.',
  compacted: '압축됨:', stopAndSend: '정지 후 전송', timeLeftHint: '남음 — 끝나면 정지 후 전송을 누르세요',
  getReady: '준비하세요…', sendingForTranscription: '답변을 전사로 보내는 중…',
  tapToAnswer: '탭하고 말로 선생님에게 답하세요', whatToAdjust: '고칠 점', inSimilarSituations: '비슷한 상황에서',
  listenAgain: '다시 듣기', betterWay: '더 나은 답변 방법', practiceAgain: '다시 연습', contextUsed: '사용된 맥락',
  compact: '압축', compactNowTitle: '지금 맥락 압축', compactUnavailable: '압축 불가', messages: '메시지',
  tokensSpent: '사용한 토큰', today: '오늘', calls: '호출', usageCostTitle: '사용량 & 비용',
  estimatedSpend: '예상 비용', thisMonth: '이번 달', usageTimeLabel: '사용 시간', perSessionAvg: '세션당 평균 비용',
  byProviderLabel: '제공자별', byFeatureLabel: '기능별', audioMinutesLabel: '오디오 분', sessionsLabel: '세션',
  usageCostNote: 'BYOK 추정치(본인 키 사용) — 가격표 기준 근사값.',
  usageCostEmpty: '아직 사용 기록이 없습니다. 문장을 몇 개 캡처하면 비용이 여기 표시됩니다.',
  onbSetupTitle: '초기 설정', welcomeTo: '환영합니다:', whichLanguage: '어떤 언어를 배우고 싶나요?',
  onbWelcomeDesc: 'PC의 모든 오디오를 수업으로 — 영상, 드라마, 팟캐스트. 여러 개를 고를 수 있습니다.',
  explanationsAppearIn: '설명과 번역이 표시되는 언어:', yourLevelEach: '각 언어의 레벨',
  levelEachDesc: '언어마다 따로입니다 — 예: 중국어 초급, 영어 고급.', levelIn: '레벨:', pickAtLeastOne: '언어를 최소 하나 고르세요',
  back: '뒤로', onbStep2: '2단계 — AI 연결(필수)', connectApiKey: 'API 키 연결',
  onbApiKeyDesc: 'Soaken은 BYOK입니다(본인 키 사용). 키가 없으면 전사와 튜터가 작동하지 않으니 계속하려면 필수입니다. 추천: Google Gemini 또는 Groq는 넉넉한 무료 등급이 있습니다.',
  checking: '확인 중...', keyConfigured: '키 설정됨 ✓ 준비 완료.', noKeyYet: '아직 키가 없습니다. 설정에서 추가하세요.',
  openSettings: '설정 열기', checkAgain: '다시 확인', onbApiKeyHint: '설정에서 키를 입력하고 돌아와 "다시 확인"을 누르세요.',
  keyRequiredToContinue: '계속하려면 키가 필요합니다', allSet: '준비 완료!', onbGoalPrefix: '오늘의 목표:',
  onbCapture5: '문장 5개 캡처', onbOf: '/', onbListenWatchHint: '무언가를 보면서 듣기를 시작하세요.',
  onbMultiLangA: '앱이 오디오 언어를 자동 감지하므로', onbMultiLangB: '개 언어가 함께 작동합니다.',
  startLearning: '학습 시작', onbStep3: '3단계 — 첫걸음', startWithWriting: '문자부터 시작',
  focusOnSpeaking: '말하기와 표현에 집중', immersion: '몰입', ofYourLanguages: '당신의 언어에서',
  startWithWritingSub: '문자 체계를 먼저 익히면 이후 모든 것이 빨라집니다.',
  focusOnSpeakingSub: '이미 이해는 됩니다 — 이제 도약은 표현입니다: 말, 발음, 대화.',
  immersionSub: '이해 가능한 콘텐츠가 연료입니다 — 보고, 캡처하고, 반복하세요.', trainProduction: '표현 연습',
  onbBullet1: '실제 대화를 캡처하고 루프/코러스로 따라 말하세요(섀도잉).',
  onbBullet2: '당신의 말을 녹음해 원본과 비교 — 발음·억양 점수.',
  onbBullet3: '아는 단어를 표시하고 문장마다 이해도 %가 오르는 걸 보세요.',
  onbBullet4: '자동 모드를 켜면 문장마다 영상이 멈춰 답할 수 있습니다.',
  channelsToStart: '시작하기 좋은 채널', levelBeginner: '제로에서 시작', levelKnowsScript: '문자를 읽을 수 있음',
  levelIntermediate: '중급', levelAdvanced: '고급 / 회화', loadingWord: '로딩 중...', reviewDone: '복습 완료!',
  youReviewed: '복습함', captureAndComeBack: '튜터 보드에서 문장을 캡처하고 나중에 다시 오세요.', reviewedCount: '복습함',
  generatingVariations: '변형 생성 중...', seeVariations: '변형 보기', otherWaysToSay: '다르게 말하는 법',
  noVariations: '변형이 없습니다.', showAnswer: '정답 보기', speakSentenceHint: '발음 연습을 위해 문장을 소리 내어 말하세요',
  gotWrong: '틀림', hard: '어려움', easy: '쉬움', pronToFix: '고칠 발음 —', wordSingular: '단어', wordsPlural: '단어',
  listenOriginalSceneVoice: '원본 발음 듣기(장면 음성)', listenCorrectTts: '올바른 발음 듣기(TTS)',
  drillHint: '🟢 원본 음성 · 🔵 TTS. 완벽해질 때까지 각 단어를 반복하세요 — 목표는 이 목록을 비우는 것.',
  tones: '성조', toneFlat: '높고 평평', toneRise: '올라감', toneFallRise: '내렸다 올라감', toneFall: '내려감',
  toneNeutral: '경성', see: '보기', you: '당신', hideComparison: '비교 숨기기', compareIntonation: '억양 비교',
  analyzingRecording: '당신의 녹음과 원본 오디오 분석 중...',
  intonationLineHint: '선은 억양(피치 상승/하강)을 나타냅니다. 파랑=당신, 초록=원본, 노랑=TTS.',
  generatingTtsBg: '백그라운드에서 TTS 생성 중...', ttsUnavailableNow: '지금 TTS를 사용할 수 없지만 원본과의 비교는 유효합니다.',
  noPitchDetected: '명확한 억양이 감지되지 않음 — 조금 더 크게 말하고 다시 녹음하세요.',
  cantReadAudio: '차트용으로 이 오디오를 읽을 수 없지만 귀로 비교할 수 있습니다:',
  chartUnavailable: '이 오디오는 차트를 사용할 수 없지만 귀로 비교할 수 있습니다:', decompose: '분해',
  analyzingWord: '분석 중', cantDecompose: '분해할 수 없음', strokes: '획', signIn: '로그인',
  createAccount: '계정 만들기', createYourAccount: '계정을 만드세요', continueWhereLeft: '하던 곳에서 계속하세요.',
  startLearningSubtitles: '실제 자막으로 학습을 시작하세요.', continueWithGoogle: 'Google로 계속하기',
  orWithEmail: '또는 이메일로', name: '이름', whatToCallYou: '어떻게 불러드릴까요?', password: '비밀번호',
  yourPassword: '비밀번호', createPassword: '비밀번호 만들기(최소 6자)', showPassword: '비밀번호 표시',
  minimize: '작업 표시줄로 최소화', rememberMe: '로그인 유지', forgotPassword: '비밀번호를 잊으셨나요?',
  iAcceptAria: '이용약관과 개인정보 처리방침을 읽고 동의합니다', iAcceptThe: '읽고 동의합니다:',
  termsOfUse: '이용약관', andThe: '및', privacyPolicy: '개인정보 처리방침', pleaseWait: '잠시만 기다리세요...',
  newHere: '처음이신가요?', createOne: '계정 만들기', haveAccount: '이미 계정이 있나요?',
  authFailed: '인증할 수 없습니다.', confirmEmail: '접근을 위해 이메일을 인증하세요.',
  accountCreated: '계정이 생성되었습니다. 로그인 중...', googleFailed: 'Google 로그인에 실패했습니다.',
  authFailedRetry: '지금 인증할 수 없습니다. 다시 시도하세요.',
}
const UI_ZH: Partial<Record<UiKey, string>> = {
  appLanguage: '应用语言', appLanguageNote: '软件文字、菜单和界面',
  explanationsLanguage: '解释和翻译', explanationsNote: '导师用此语言回答',
  yourLanguage: '我的语言', contentLanguage: '内容语言', contentLanguageLabel: '你观看的音频语言',
  contentLanguageNote: '"自动"按片段检测；如果检测错误（例如英语被识别为中文），请固定语言。',
  configured: '已配置', settings: '设置', activeProvider: '当前提供方',
  aiProviders: 'AI 提供方 — 你的密钥，你的额度', tutorAi: '导师 AI', transcription: '转录',
  configureProvider: '请在上方至少配置一个提供方以启用功能。', ttsVoice: 'TTS 语音', engine: '引擎',
  kokoroVoice: 'Kokoro 语音', kokoroNote: '当文本为英语时使用',
  kokoroFirstUse: '首次使用 Kokoro 会下载本地模型；之后单词和句子会被缓存。',
  shortcuts: '全局快捷键', about: '关于', saved: '已保存', test: '测试', testing: '测试中...',
  shortcutListen: '开始 / 停止收听', shortcutDashboard: '打开主页', shortcutSettings: '打开设置',
  shortcutTutorBoard: '打开导师板', shortcutDock: '显示 / 隐藏 dock', shortcutPlayer: '暂停 / 继续播放器',
  appTagline: '沉浸在语言中',
  aboutDescription: '面向任何语言的悬浮导师。Soaken 监听你电脑上的任何音频（视频、通话、影视），把它变成真正的口语和发音练习。',
  ttsLocalVoice: '本地英语语音', ttsMultiFallback: '多语言后备', forvoKeyPlaceholder: 'Forvo API 密钥',
  keyValid: '密钥有效 ✓', keyTestFailed: '测试失败', logout: '退出登录',
  logoutConfirm: '你需要重新登录才能使用应用。',
  audioLangTitle: '音频语言 — 点击切换。锁定正确语言可大幅提升转录准确度（自动可能识别错误）。',
  audioSection: '音频', micYourVoice: '麦克风（你的声音）', micYourVoiceNote: '用于发音练习（当你说话时）。',
  transcribeSource: '转录哪个来源', transcribeSourceNote: '应用监听并转录的来源。',
  systemAudioOption: '🔊 电脑声音（视频、通话）', defaultMic: '默认麦克风', removeKey: '删除密钥',
  getKey: '获取密钥', cancel: '取消', edit: '编辑', add: '+ 添加', save: '保存', noneConfigured: '未配置',
  dashboardTitle: '主页', review: '复习', tutorBoard: '导师板', floatingBar: '悬浮栏', welcome: '欢迎回来',
  ready: '今天准备好练习了吗？你有', phrase: '个句子', phrases: '个句子', toReview: '待复习。',
  sessions: '会话', streak: '连续', days: '天', todayGoal: '今日目标', goalHit: '目标完成！',
  remaining: '剩余', startListeningHint: '开始收听：', reviewByLanguage: '按语言复习',
  nothingDue: '现在没有需要复习的', dueSuffix: '待复习', upToDate: '已是最新', reviewAll: '全部复习',
  pending: '待处理', topMistakes: '最常错的单词', topMistakesEmpty: '首次练习后，常错单词会显示在这里。',
  recentSessions: '最近会话', capturedSession: '已捕获会话', quickShortcuts: '快捷键',
  showHideBar: '显示/隐藏栏', startPrompt: '使用', toStart: '开始。',
  pronTestTitle: '测试我的发音', pronTestSub: '大声朗读一句话，获得真实的发音 + 语调评分。', start: '开始',
  pronProfileTitle: '你的发音画像', pronProfileEmpty: '在导师板练习几句话，发现你的发音薄弱点。',
  pronSoundsYouMiss: '最常忽略的发音', pronWordsToTrain: '要练习的单词', pronTrainButton: '练习发音',
  listen: '收听', pronDiagTitle: '发音诊断', pronDrillTitle: '练习薄弱单词', trainSessionMistakes: '练习本次的错误',
  pronDiagSubAi: 'AI 不只看文字，还会听你的声音', pronDiagSubDrill: '朗读你最常错的单词并获得评分',
  pronUnavailable: '暂不支持诊断：', close: '关闭', readAloudFocus: '大声朗读 — 重点：', listenModel: '听示范',
  wordByWord: '逐词', tips: '提示', words: '单词', intonation: '语调', transcribing: '转录中…',
  analyzing: '正在分析你的发音…', speak: '说话', stop: '停止', tryAgain: '再试一次', redo: '重做',
  next: '下一个', nextSentence: '下一句', waitingAudio: '等待音频...', waitingAudioSub: '分析会自动显示在这里。',
  capturedThisSession: '本次会话捕获', speedTitle: '音频速度（原声/TTS）。0.8× 很适合练习听力。',
  chatWithTeacher: '与老师对话', teacherIn: '老师语言', teacherReadyTitle: '就你看的内容与老师对话',
  captureMore: '捕获', toUnlockTeacher: '句后解锁老师', knownWordsSuffix: '已认识', coverage: '理解度',
  naturalSpeech: '自然口语', spokenPinyin: '口语拼音', realPronunciation: '真实发音', speaking: '播放中',
  practice: '练习', accuracy: '准确度', vocabulary: '词汇', analysisFailed: '分析失败：',
  listenOriginalScene: '听原场景音频',
  loopTitle: '循环：以所选速度把句子重复 3 次，并留出停顿让你跟读（影子跟读）',
  listenTtsTitle: '听合成语音（TTS）', practicePronTitle: '练习发音', mark: '标记', accents: '口音',
  nativeVoices: '母语者', nativeVoiceN: '语音', nativePronTitle: '母语者发音（Forvo）',
  nativePronNote: '真实母语者语音。Wikimedia/Lingua Libre 免费即可使用，无需密钥。添加 Forvo 密钥（有免费额度）可获得更好覆盖。',
  iKnow: '我认识', learningWord: '学习中', ignoreWord: '忽略', markAs: '标记为', clickToUnmark: '点击取消标记',
  goodPronunciation: '发音不错！', heard: '听到：', searchingMeaning: '正在查询含义...', noMeaning: '没有可用的含义。',
  trainThisWord: '练习这个词', listenOriginalWord: '听这个词的原始发音', listenApproxWord: '听这个词的大致片段',
  listenWord: '听单词', listenSee: '听/看', knownWordTitle: '你已标记为认识', learningWordTitle: '你正在学习这个词',
  ignoreWordTitle: '已忽略（专有名词等）', clickToHear: '点击听并查看含义', badgeAllKnown: '这句话里的每个词你都认识',
  badgePlusOne: '理想的"+1"：这句话只有 1 个新词', badgeNewWords: '个新词', milestoneRemaining: '还差',
  milestoneForMark: '即可达到', milestoneWords: '个词', milestoneAllDone: '你通过了所有里程碑！🎉',
  romanization: '罗马音', transliteration: '音译', tabTranscription: '转录', tabSession: '会话',
  sessionTimeTitle: '当前会话时长', live: 'LIVE', hide: '隐藏', processing: '处理中', listenStart: '收听',
  autoPracticeTitle: '每句暂停视频，方便你练习', autoPractice: '自动练习', analyze: '分析', level: '等级',
  speechThreshold: '语音阈值', repeatSentence: '重复句子', listenTtsClear: '听合成语音（清晰/缓慢）',
  listenMyRecording: '听我的录音', myVoice: '我的声音', recordingIn: '录音倒计时', recordingNow: '录音中 - 现在说话',
  evaluating: '评估中...', clickRecordWhenReady: '准备好后点击录音。', record: '录音', repeatAgain: '重复',
  continueWord: '继续', skip: '跳过', pressListenHint: '点击收听并播放视频。', audioLabel: '音频', capturing: '捕获中...',
  downloadingVoice: '正在下载本地语音…', practiceSpeechHere: '你的练习记录会显示在这里。',
  practiceHint: '在导师板用"练习"录音并比较。', attempt: '尝试', youSaid: '你说的',
  noSystemAudio: '没有系统音频。请播放一些内容后重试。', audioDisconnected: '音频已断开。点击重新开始。',
  recorderError: '录音错误。', voiceChatBasedOn: '语音对话 — 基于', fromThisSession: '本次会话',
  teacherThinking: '老师正在思考…', teacherUnavailable: '现在无法连接到老师。', notEnoughOldContext: '尚无足够的旧上下文可压缩。',
  compacted: '已压缩：', stopAndSend: '停止并发送', timeLeftHint: '剩余 — 完成后点击停止并发送',
  getReady: '准备…', sendingForTranscription: '正在发送你的回答进行转录…', tapToAnswer: '点按并开口回答老师',
  whatToAdjust: '需要调整的地方', inSimilarSituations: '在类似情境中', listenAgain: '再听一次',
  betterWay: '更好的回答方式', practiceAgain: '再次练习', contextUsed: '使用的上下文', compact: '压缩',
  compactNowTitle: '立即压缩上下文', compactUnavailable: '无法压缩', messages: '条消息', tokensSpent: '已用额度',
  today: '今天', calls: '次调用', usageCostTitle: '用量与费用', estimatedSpend: '预估花费', thisMonth: '本月',
  usageTimeLabel: '使用时长', perSessionAvg: '每会话平均费用', byProviderLabel: '按提供方', byFeatureLabel: '按功能',
  audioMinutesLabel: '分钟音频', sessionsLabel: '会话', usageCostNote: 'BYOK 预估（你使用自己的密钥）— 按价格表的近似值。',
  usageCostEmpty: '暂无用量记录。捕获几句话即可在此看到费用。', onbSetupTitle: '初始设置', welcomeTo: '欢迎来到',
  whichLanguage: '你想学哪种语言？', onbWelcomeDesc: '把任何电脑音频变成课程 — 视频、影视、播客。可以选多个。',
  explanationsAppearIn: '解释和翻译显示的语言：', yourLevelEach: '你在每种语言的等级',
  levelEachDesc: '每种语言各自独立 — 例如中文初级、英语高级。', levelIn: '等级：', pickAtLeastOne: '至少选择一种语言',
  back: '返回', onbStep2: '第 2 步 — 连接 AI（必需）', connectApiKey: '连接 API 密钥',
  onbApiKeyDesc: 'Soaken 采用 BYOK（你使用自己的密钥）。没有它，转录和导师无法工作，所以继续前必需。推荐：Google Gemini 或 Groq 有慷慨的免费额度。',
  checking: '检查中...', keyConfigured: '密钥已配置 ✓ 一切就绪。', noKeyYet: '还没有密钥。打开设置添加。',
  openSettings: '打开设置', checkAgain: '重新检查', onbApiKeyHint: '在设置中填入密钥后回到这里，再点"重新检查"。',
  keyRequiredToContinue: '继续需要一个密钥', allSet: '一切就绪！', onbGoalPrefix: '你今天的目标：',
  onbCapture5: '捕获 5 个句子', onbOf: '/', onbListenWatchHint: '一边看内容一边开始收听。',
  onbMultiLangA: '应用会自动检测音频语言，所以你的', onbMultiLangB: '种语言可一起使用。', startLearning: '开始学习',
  onbStep3: '第 3 步 — 第一步', startWithWriting: '从文字开始', focusOnSpeaking: '专注口语和表达', immersion: '沉浸',
  ofYourLanguages: '在你的语言中', startWithWritingSub: '先学会书写系统会加快之后的一切。',
  focusOnSpeakingSub: '你已经能理解 — 现在的飞跃是表达：说话、发音和对话。',
  immersionSub: '可理解的内容是燃料 — 观看、捕获、重复。', trainProduction: '训练表达',
  onbBullet1: '捕获真实对话，用循环/合唱跟读（影子跟读）。', onbBullet2: '录下你的发音并与原声比较 — 发音和语调评分。',
  onbBullet3: '标记已认识的词，看着理解度 % 一句句上升。', onbBullet4: '打开自动模式，视频会在每句暂停让你回答。',
  channelsToStart: '入门频道', levelBeginner: '从零开始', levelKnowsScript: '我能读文字', levelIntermediate: '中级',
  levelAdvanced: '高级 / 会话', loadingWord: '加载中...', reviewDone: '复习完成！', youReviewed: '你复习了',
  captureAndComeBack: '在导师板捕获句子，稍后再回来。', reviewedCount: '已复习', generatingVariations: '生成变体中...',
  seeVariations: '查看变体', otherWaysToSay: '其他说法', noVariations: '没有可用的变体。', showAnswer: '显示答案',
  speakSentenceHint: '大声说出这句话来练习发音', gotWrong: '答错了', hard: '困难', easy: '容易',
  pronToFix: '需改进的发音 —', wordSingular: '个词', wordsPlural: '个词', listenOriginalSceneVoice: '听原始发音（场景语音）',
  listenCorrectTts: '听正确发音（TTS）', drillHint: '🟢 原声 · 🔵 TTS。反复练每个词直到掌握 — 目标是清空这个列表。',
  tones: '声调', toneFlat: '高平', toneRise: '上升', toneFallRise: '降升', toneFall: '下降', toneNeutral: '轻声',
  see: '查看', you: '你', hideComparison: '隐藏对比', compareIntonation: '对比语调',
  analyzingRecording: '正在分析你的录音和原始音频...',
  intonationLineHint: '曲线显示语调（音高升降）。蓝=你，绿=原声，黄=TTS。', generatingTtsBg: '正在后台生成 TTS...',
  ttsUnavailableNow: '现在无法使用 TTS，但与原声的对比仍然有效。',
  noPitchDetected: '未检测到清晰语调 — 请说大声一点并重新录音。',
  cantReadAudio: '无法读取此音频用于图表，但你可以用耳朵比较：',
  chartUnavailable: '此音频无法生成图表，但你可以用耳朵比较：', decompose: '拆解', analyzingWord: '分析中',
  cantDecompose: '无法拆解', strokes: '笔画', signIn: '登录', createAccount: '创建账户', createYourAccount: '创建你的账户',
  continueWhereLeft: '从上次的地方继续。', startLearningSubtitles: '用真实字幕开始学习。', continueWithGoogle: '使用 Google 继续',
  orWithEmail: '或用邮箱', name: '姓名', whatToCallYou: '我们该怎么称呼你？', password: '密码', yourPassword: '你的密码',
  createPassword: '创建密码（至少 6 位）', showPassword: '显示密码', minimize: '最小化到任务栏', rememberMe: '记住我',
  forgotPassword: '忘记密码？', iAcceptAria: '我已阅读并接受使用条款和隐私政策', iAcceptThe: '我已阅读并接受',
  termsOfUse: '使用条款', andThe: '和', privacyPolicy: '隐私政策', pleaseWait: '请稍候...', newHere: '第一次来？',
  createOne: '创建账户', haveAccount: '已有账户？', authFailed: '无法验证身份。', confirmEmail: '请验证你的邮箱以解锁访问。',
  accountCreated: '账户创建成功。正在登录...', googleFailed: '无法使用 Google 登录。',
  authFailedRetry: '现在无法验证身份。请重试。',
}

const UI_TABLES: Record<AppLanguage, Partial<Record<UiKey, string>>> = {
  pt: UI.pt, en: UI.en, ko: UI_KO, zh: UI_ZH,
}

/** Texto da UI: usa a tabela do idioma; o que faltar cai no INGLÊS (e por fim no pt). */
export function uiText(lang: AppLanguage, key: UiKey): string {
  return UI_TABLES[lang]?.[key] ?? UI.en[key] ?? UI.pt[key]
}
